<?php
namespace Database\Seeders;
use App\Enums\UserRole; use App\Models\{Checklist,CorrectiveAction,Department,Incident,Inspection,Risk,User}; use Illuminate\Database\Seeder; use Illuminate\Support\Facades\Hash;
class DatabaseSeeder extends Seeder {
 public function run():void {
  $production=Department::create(['name'=>'تولید','code'=>'PRD','location'=>'سالن اصلی']);$maintenance=Department::create(['name'=>'تعمیرات و نگهداری','code'=>'MNT','location'=>'کارگاه فنی']);$office=Department::create(['name'=>'اداری و منابع انسانی','code'=>'ADM','location'=>'ساختمان اداری']);
  $admin=User::create(['name'=>'مدیر سامانه','personnel_code'=>'1001','email'=>'admin@hse.test','phone'=>'09120000001','password'=>Hash::make('password'),'role'=>UserRole::Admin,'is_active'=>true]);
  $hse=User::create(['name'=>'مسئول HSE','personnel_code'=>'1002','email'=>'manager@hse.test','phone'=>'09120000002','password'=>Hash::make('password'),'role'=>UserRole::HseManager,'department_id'=>$office->id,'is_active'=>true]);
  $unit=User::create(['name'=>'مدیر واحد تولید','personnel_code'=>'1003','email'=>'unit@hse.test','phone'=>'09120000003','password'=>Hash::make('password'),'role'=>UserRole::UnitManager,'department_id'=>$production->id,'is_active'=>true]);
  $inspector=User::create(['name'=>'بازرس ایمنی','personnel_code'=>'1004','email'=>'inspector@hse.test','phone'=>'09120000004','password'=>Hash::make('password'),'role'=>UserRole::Inspector,'department_id'=>$office->id,'is_active'=>true]);$production->update(['manager_id'=>$unit->id]);
  $check=Checklist::create(['title'=>'بازرسی ایمنی عمومی محیط کار','category'=>'ایمنی عمومی','description'=>'کنترل شرایط عمومی ایمنی، نظم، حریق و تجهیزات حفاظت فردی','version'=>'1.0','created_by'=>$hse->id]);foreach([['مسیرهای تردد و خروج اضطراری باز و بدون مانع هستند؟',true,3],['کپسول‌های آتش‌نشانی در دسترس و دارای اعتبار هستند؟',true,3],['کارکنان از تجهیزات حفاظت فردی مناسب استفاده می‌کنند؟',true,3],['تابلوها و علائم هشداردهنده در محل مناسب نصب شده‌اند؟',false,2],['محیط کار دارای نظم و نظافت قابل قبول است؟',false,1]] as $i=>$v)$check->items()->create(['question'=>$v[0],'is_critical'=>$v[1],'weight'=>$v[2],'sort_order'=>$i]);
  Inspection::create(['code'=>'INS-DEMO-001','title'=>'بازرسی هفتگی سالن تولید','checklist_id'=>$check->id,'department_id'=>$production->id,'inspector_id'=>$inspector->id,'scheduled_at'=>now()->addDay(),'status'=>'planned','location'=>'سالن تولید']);
  $risk=Risk::create(['code'=>'RSK-DEMO-001','title'=>'حفاظ نامناسب دستگاه پرس','description'=>'امکان تماس دست اپراتور با منطقه خطر حین عملکرد دستگاه','category'=>'ایمنی ماشین‌آلات','department_id'=>$production->id,'identified_by'=>$inspector->id,'likelihood'=>4,'severity'=>5,'risk_score'=>20,'risk_level'=>'بحرانی','existing_controls'=>'آموزش شفاهی اپراتور','proposed_controls'=>'نصب حفاظ اینترلاک و بازنگری دستورالعمل','status'=>'open']);
  CorrectiveAction::create(['code'=>'ACT-DEMO-001','title'=>'نصب حفاظ اینترلاک دستگاه پرس','description'=>'طراحی، نصب و تست حفاظ اینترلاک؛ معیار پذیرش: توقف فوری دستگاه با بازشدن حفاظ','actionable_type'=>$risk::class,'actionable_id'=>$risk->id,'department_id'=>$maintenance->id,'assignee_id'=>$unit->id,'assigned_by'=>$hse->id,'priority'=>'critical','due_date'=>today()->addDays(5),'status'=>'assigned']);
  Incident::create(['code'=>'INC-DEMO-001','type'=>'near_miss','title'=>'لغزش بدون آسیب کنار خط مونتاژ','description'=>'کارگر به دلیل وجود لکه روغن لغزید اما دچار آسیب نشد.','department_id'=>$production->id,'reported_by'=>$inspector->id,'occurred_at'=>now()->subDays(2),'location'=>'خط مونتاژ شماره ۲','lost_days'=>0,'immediate_actions'=>'پاک‌سازی محل و نصب تابلوی هشدار','status'=>'investigating']);
 }
}
