@extends('layouts.app')
@section('title',$incident->code)
@section('page-title','پرونده رویداد')
@section('content')
@php
    $categories = ['people'=>'افراد','machine'=>'ماشین','method'=>'روش','material'=>'مواد','environment'=>'محیط','management'=>'مدیریت'];
    $fishboneData = $incident->fishbone ?? [];
    $treeData = $incident->fault_tree ?? [];
    $treeNodes = [];
    foreach ($treeData as $index => $node) {
        if (is_array($node)) {
            $treeNodes[] = ['id'=>$node['id'] ?? 'node-'.$index, 'label'=>$node['label'] ?? '', 'parent_id'=>$node['parent_id'] ?? null, 'relation'=>$node['relation'] ?? 'OR'];
        } elseif (filled($node)) {
            $treeNodes[] = ['id'=>'node-'.$index, 'label'=>$node, 'parent_id'=>$index ? 'node-'.($index - 1) : null, 'relation'=>'OR'];
        }
    }
    if (!$treeNodes) $treeNodes[] = ['id'=>'root', 'label'=>'رویداد نهایی', 'parent_id'=>null, 'relation'=>'OR'];
@endphp
<div class="grid gap-6 lg:grid-cols-[1fr_340px]"><section class="space-y-5"><div class="rounded-2xl border bg-white p-6"><div class="flex justify-between"><div><span class="text-xs text-slate-400">{{ $incident->code }}</span><h2 class="mt-2 text-xl font-black">{{ $incident->title }}</h2></div><x-status :status="$incident->status" /></div><p class="mt-5 whitespace-pre-line text-sm leading-7">{{ $incident->description }}</p><div class="mt-5 grid gap-3 md:grid-cols-2"><div class="rounded-xl bg-amber-50 p-4"><small class="font-bold text-amber-700">اقدامات فوری</small><p class="mt-2 text-sm">{{ $incident->immediate_actions?:'ثبت نشده' }}</p></div><div class="rounded-xl bg-slate-50 p-4"><small class="font-bold text-slate-500">پیامد و افراد</small><p class="mt-2 text-sm">{{ $incident->consequences?:'—' }}</p><p class="mt-2 text-xs text-slate-500">{{ implode('، ',$incident->involved_people??[])?:'فردی ثبت نشده' }}</p></div></div>@if($incident->attachments->count())<div class="mt-4 flex flex-wrap gap-2">@foreach($incident->attachments as $f)<a target="_blank" href="{{ Storage::url($f->path) }}" class="rounded-lg bg-slate-100 px-3 py-2 text-xs font-bold text-emerald-700">{{ $f->original_name }}</a>@endforeach</div>@endif</div>
@if(auth()->user()->hasRole(['admin','hse_manager']))<form method="post" action="{{ route('incidents.investigate',$incident) }}" class="rounded-2xl border bg-white p-6">@csrf @method('PATCH')<h3 class="font-black">تحلیل علت ریشه‌ای RCA</h3><p class="mt-1 text-xs text-slate-400">فقط روش انتخاب‌شده اعتبارسنجی و ذخیره می‌شود؛ اطلاعات روش‌های دیگر حفظ خواهد شد.</p><div class="mt-4 grid gap-4 md:grid-cols-2"><label><span class="mb-2 block text-sm font-bold">روش RCA *</span><select id="rca-method" name="rca_method" class="w-full rounded-xl border p-3">@foreach(['five_whys'=>'۵ چرا','fishbone'=>'استخوان ماهی','fault_tree'=>'درخت خطا','combined'=>'ترکیبی'] as $k=>$v)<option value="{{ $k }}" @selected($incident->rca_method===$k)>{{ $v }}</option>@endforeach</select></label><label><span class="mb-2 block text-sm font-bold">وضعیت *</span><select name="status" class="w-full rounded-xl border p-3">@foreach(['investigating'=>'در حال بررسی','actions_pending'=>'منتظر اقدام','closed'=>'بسته'] as $k=>$v)<option value="{{ $k }}" @selected($incident->status===$k)>{{ $v }}</option>@endforeach</select></label><label class="md:col-span-2"><span class="mb-2 block text-sm font-bold">جمع‌بندی علت ریشه‌ای *</span><textarea name="root_cause" required rows="4" class="w-full rounded-xl border bg-slate-50 p-4">{{ $incident->root_cause }}</textarea></label></div>
<div data-rca-panel="five_whys" class="mt-5 rounded-xl border border-sky-200 bg-sky-50 p-4"><h4 class="font-bold">۵ چرا، زنجیره علت</h4><div class="mt-3 space-y-2">@for($i=0;$i<5;$i++)<div class="flex items-center gap-2"><span class="grid h-8 w-8 shrink-0 place-items-center rounded-full bg-sky-600 text-xs font-black text-white">{{ $i+1 }}</span><input name="five_whys[]" value="{{ $incident->five_whys[$i]??'' }}" placeholder="چرا {{ $i+1 }}؟ علت مرحله قبل را بنویسید" class="w-full rounded-lg border bg-white p-2 text-sm"><span class="text-sky-500">↓</span></div>@endfor</div></div>
<div data-rca-panel="fishbone" class="mt-5 rounded-xl border border-amber-200 bg-amber-50 p-4"><div class="flex items-center justify-between"><h4 class="font-bold">استخوان ماهی</h4><span class="text-xs text-amber-700">برای هر دسته چند علت اضافه کنید</span></div><div class="relative mt-5 overflow-x-auto rounded-xl bg-white p-4"><div class="fishbone-diagram"><div class="fishbone-spine"></div>@foreach($categories as $category=>$label)@php $causes=$fishboneData[$category]??[]; $causes=is_array($causes)?$causes:[$causes]; @endphp<div class="fishbone-branch"><strong>{{ $label }}</strong><div data-fishbone-category="{{ $category }}" class="space-y-2">@foreach($causes as $cause)@if(filled($cause))<div class="flex gap-2"><input name="fishbone[{{ $category }}][]" value="{{ $cause }}" class="w-full rounded-lg border p-2 text-sm"><button type="button" data-remove-row class="px-2 text-rose-500" title="حذف علت">×</button></div>@endif @endforeach<div class="flex gap-2"><input name="fishbone[{{ $category }}][]" placeholder="علت جدید" class="w-full rounded-lg border p-2 text-sm"><button type="button" data-remove-row class="hidden px-2 text-rose-500" title="حذف علت">×</button></div></div><button type="button" data-add-cause="{{ $category }}" class="mt-2 text-xs font-bold text-amber-700">+ افزودن علت</button></div>@endforeach<div class="fishbone-effect">حادثه / رویداد اصلی</div></div></div></div>
<div data-rca-panel="fault_tree" class="mt-5 rounded-xl border border-emerald-200 bg-emerald-50 p-4"><div class="flex items-center justify-between"><h4 class="font-bold">درخت خطا</h4><button type="button" id="add-tree-node" class="rounded-lg bg-emerald-700 px-3 py-2 text-xs font-bold text-white">+ افزودن گره</button></div><p class="mt-2 text-xs text-slate-500">برای هر علت، گره والد و رابطه منطقی AND / OR را مشخص کنید.</p><div id="fault-tree-nodes" class="fault-tree-nodes mt-4 space-y-3">@foreach($treeNodes as $index=>$node)<div data-tree-node class="fault-tree-node rounded-xl border bg-white p-3 shadow-sm"><div class="mb-2 flex items-center justify-between"><span class="text-xs font-black text-emerald-700">گره {{ $index+1 }}</span><button type="button" data-remove-node class="text-xs font-bold text-rose-500">حذف</button></div><div class="grid gap-2 md:grid-cols-4"><input type="hidden" name="fault_tree[nodes][{{ $index }}][id]" value="{{ $node['id'] }}" data-tree-id><input name="fault_tree[nodes][{{ $index }}][label]" value="{{ $node['label'] }}" placeholder="شرح علت یا رویداد" required class="rounded-lg border p-2 text-sm md:col-span-2"><select name="fault_tree[nodes][{{ $index }}][parent_id]" data-tree-parent class="rounded-lg border p-2 text-sm"><option value="">والد اصلی</option>@foreach($treeNodes as $parent)<option value="{{ $parent['id'] }}" @selected($node['parent_id']===$parent['id'])>{{ $parent['label'] ?: $parent['id'] }}</option>@endforeach</select><select name="fault_tree[nodes][{{ $index }}][relation]" class="rounded-lg border p-2 text-sm"><option value="OR" @selected($node['relation']==='OR')>OR</option><option value="AND" @selected($node['relation']==='AND')>AND</option></select></div></div>@endforeach</div><template id="tree-node-template"><div data-tree-node class="fault-tree-node rounded-xl border bg-white p-3 shadow-sm"><div class="mb-2 flex items-center justify-between"><span class="text-xs font-black text-emerald-700">گره جدید</span><button type="button" data-remove-node class="text-xs font-bold text-rose-500">حذف</button></div><div class="grid gap-2 md:grid-cols-4"><input type="hidden" data-tree-id><input data-tree-label placeholder="شرح علت یا رویداد" required class="rounded-lg border p-2 text-sm md:col-span-2"><select data-tree-parent class="rounded-lg border p-2 text-sm"><option value="">والد اصلی</option></select><select data-tree-relation class="rounded-lg border p-2 text-sm"><option value="OR">OR</option><option value="AND">AND</option></select></div></div></template></div>
<button class="mt-5 rounded-xl bg-slate-900 px-5 py-3 text-sm font-bold text-white">ثبت RCA</button></form>@endif
<div class="rounded-2xl border bg-white p-6"><div class="flex justify-between"><h3 class="font-black">اقدامات پیشگیرانه و اصلاحی</h3><a href="{{ route('actions.create',['incident'=>$incident->id]) }}" class="text-xs font-bold text-emerald-600">+ ایجاد CAPA از RCA</a></div><div class="mt-4 divide-y">@forelse($incident->actions as $a)<a href="{{ route('actions.show',$a) }}" class="flex justify-between py-3"><div><b class="text-sm">{{ $a->title }}</b><div class="text-xs text-slate-400">{{ $a->assignee->name }}</div></div><x-status :status="$a->status" /></a>@empty<p class="py-6 text-center text-sm text-slate-400">اقدامی تعریف نشده است.</p>@endforelse</div></div></section><aside><div class="sticky top-24 rounded-2xl border bg-white p-6"><h3 class="font-black">مشخصات رویداد</h3><dl class="mt-5 space-y-4 text-sm">@foreach([['نوع',['incident'=>'حادثه','near_miss'=>'شبه‌حادثه','occupational_disease'=>'بیماری شغلی','environmental'=>'محیط‌زیستی'][$incident->type]],['واحد',$incident->department->name],['محل',$incident->location],['فعالیت',$incident->activity?:'—'],['زمان',\Morilog\Jalali\Jalalian::fromCarbon($incident->occurred_at)->format('Y/m/d H:i')],['گزارش‌دهنده',$incident->reporter->name],['سطح آسیب',$incident->injury_level?:'—'],['روز از دست‌رفته',$incident->lost_days]] as [$k,$v])<div class="flex justify-between gap-4"><dt class="text-slate-400">{{ $k }}</dt><dd class="text-left font-bold">{{ $v }}</dd></div>@endforeach</dl></div></aside></div>
<script>
(() => {
    const methodSelect = document.getElementById('rca-method');
    const panels = document.querySelectorAll('[data-rca-panel]');
    const syncPanels = () => { const method = methodSelect.value; panels.forEach(panel => { const active = method === 'combined' || method === panel.dataset.rcaPanel; panel.classList.toggle('hidden', !active); panel.querySelectorAll('input,select,textarea').forEach(input => { input.disabled = !active; }); }); };
    methodSelect?.addEventListener('change', syncPanels); syncPanels();
    document.querySelectorAll('[data-add-cause]').forEach(button => button.addEventListener('click', () => { const list = document.querySelector(`[data-fishbone-category="${button.dataset.addCause}"]`); const row = document.createElement('div'); row.className = 'flex gap-2'; row.innerHTML = `<input name="fishbone[${button.dataset.addCause}][]" placeholder="علت جدید" class="w-full rounded-lg border p-2 text-sm"><button type="button" data-remove-row class="px-2 text-rose-500" title="حذف علت">×</button>`; list.appendChild(row); }));
    document.addEventListener('click', event => { if (event.target.matches('[data-remove-row]')) event.target.closest('.flex')?.remove(); if (event.target.matches('[data-remove-node]')) { event.target.closest('[data-tree-node]')?.remove(); refreshParents(); } });
    const treeList = document.getElementById('fault-tree-nodes'); const template = document.getElementById('tree-node-template');
    const refreshParents = () => { const nodes = [...treeList.querySelectorAll('[data-tree-node]')]; nodes.forEach((node, index) => { const idInput = node.querySelector('[data-tree-id]'); const id = idInput.value || `node-${Date.now()}-${index}`; idInput.value = id; node.querySelectorAll('[name]').forEach(input => { input.name = input.name.replace(/nodes\]\[\d+\]/, `nodes][${index}]`); }); const select = node.querySelector('[data-tree-parent]'); const current = select.value; select.innerHTML = '<option value="">والد اصلی</option>'; nodes.forEach(parent => { if (parent !== node) { const parentId = parent.querySelector('[data-tree-id]').value; const label = parent.querySelector('[data-tree-label], [name$="[label]"]')?.value || parentId; const option = new Option(label, parentId); option.selected = parentId === current; select.add(option); } }); }); };
    document.getElementById('add-tree-node')?.addEventListener('click', () => { const index = treeList.querySelectorAll('[data-tree-node]').length; const node = template.content.cloneNode(true); const wrapper = node.querySelector('[data-tree-node]'); wrapper.querySelector('[data-tree-id]').name = `fault_tree[nodes][${index}][id]`; wrapper.querySelector('[data-tree-id]').value = `node-${Date.now()}`; wrapper.querySelector('[data-tree-label]').name = `fault_tree[nodes][${index}][label]`; wrapper.querySelector('[data-tree-parent]').name = `fault_tree[nodes][${index}][parent_id]`; wrapper.querySelector('[data-tree-relation]').name = `fault_tree[nodes][${index}][relation]`; treeList.appendChild(node); refreshParents(); });
    treeList?.addEventListener('input', event => { if (event.target.matches('[data-tree-label], [name$="[label]"]')) refreshParents(); }); refreshParents();
})();
</script>
@endsection