@extends('layouts.app') @php $editing=$profile->exists; @endphp @section('title',$editing?'ویرایش پرونده سلامت':'پرونده سلامت جدید') @section('page-title',$editing?'ویرایش پرونده سلامت':'ایجاد پرونده سلامت') @section('content')
<form method="post" action="{{ $editing?route('health.profiles.update',$profile):route('health.profiles.store') }}" class="mx-auto max-w-5xl">@csrf @if($editing)@method('PUT')@endif
<div class="rounded-3xl border border-slate-200 bg-white shadow-sm"><div class="border-b border-slate-200 bg-gradient-to-l from-sky-50 to-white p-6"><h2 class="text-lg font-black">مشخصات شغلی و وضعیت سلامت</h2><p class="mt-1 text-xs text-slate-500">اطلاعات لازم برای مدیریت طب کار؛ از ثبت جزئیات پزشکی غیرضروری خودداری کنید.</p></div><div class="grid gap-5 p-6 md:grid-cols-2">
<label class="block"><span class="mb-2 block text-sm font-bold">کارمند *</span><select name="user_id" class="w-full rounded-xl border border-slate-200 px-4 py-3" @disabled($editing)>@foreach($users as $u)<option value="{{ $u->id }}" @selected(old('user_id',$profile->user_id)==$u->id)>{{ $u->name }} — {{ $u->personnel_code }} — {{ $u->department?->name }}</option>@endforeach</select>@if($editing)<input type="hidden" name="user_id" value="{{ $profile->user_id }}">@endif</label>
<label><span class="mb-2 block text-sm font-bold">عنوان شغلی *</span><input name="job_title" value="{{ old('job_title',$profile->job_title) }}" class="w-full rounded-xl border border-slate-200 px-4 py-3" required></label>
<label><span class="mb-2 block text-sm font-bold">تاریخ شروع به کار</span><input name="employment_start_date" value="{{ old('employment_start_date',$profile->employment_start_date?jdate($profile->employment_start_date)->format('Y/m/d'):'') }}" class="w-full rounded-xl border border-slate-200 px-4 py-3"></label>
<label><span class="mb-2 block text-sm font-bold">صلاحیت پزشکی *</span><select name="fitness_status" class="w-full rounded-xl border border-slate-200 px-4 py-3">@foreach(['fit'=>'مجاز به کار','fit_with_restrictions'=>'مجاز با محدودیت','temporarily_unfit'=>'عدم صلاحیت موقت','unfit'=>'عدم صلاحیت','pending'=>'در انتظار ارزیابی'] as $k=>$v)<option value="{{ $k }}" @selected(old('fitness_status',$profile->fitness_status?:'pending')===$k)>{{ $v }}</option>@endforeach</select></label>
<label class="md:col-span-2"><span class="mb-2 block text-sm font-bold">محدودیت‌های شغلی</span><textarea name="medical_restrictions" rows="3" class="w-full rounded-xl border border-slate-200 px-4 py-3" placeholder="فقط محدودیت مرتبط با کار؛ نه شرح تشخیص پزشکی">{{ old('medical_restrictions',$profile->medical_restrictions) }}</textarea></label>
<div class="rounded-2xl border border-amber-200 bg-amber-50 p-4 md:col-span-2"><label class="flex items-center gap-2 font-bold text-amber-900"><input type="checkbox" name="follow_up_required" value="1" @checked(old('follow_up_required',$profile->follow_up_required))> نیازمند پیگیری پزشکی</label><div class="mt-3"><span class="mb-2 block text-xs font-bold text-amber-800">تاریخ پیگیری</span><input name="follow_up_date" value="{{ old('follow_up_date',$profile->follow_up_date?jdate($profile->follow_up_date)->format('Y/m/d'):'') }}" class="w-full rounded-xl border border-amber-200 bg-white px-4 py-3 md:w-72"></div></div>
<label><span class="mb-2 block text-sm font-bold">وضعیت بیماری شغلی</span><select name="occupational_disease_status" class="w-full rounded-xl border border-slate-200 px-4 py-3">@foreach(['none'=>'بدون مورد ثبت‌شده','suspected'=>'مشکوک','confirmed'=>'تأییدشده','under_review'=>'در حال بررسی'] as $k=>$v)<option value="{{ $k }}" @selected(old('occupational_disease_status',$profile->occupational_disease_status?:'none')===$k)>{{ $v }}</option>@endforeach</select></label>
<label class="md:col-span-2"><span class="mb-2 block text-sm font-bold">یادداشت داخلی</span><textarea name="notes" rows="3" class="w-full rounded-xl border border-slate-200 px-4 py-3">{{ old('notes',$profile->notes) }}</textarea></label>
</div></div><div class="mt-5 flex justify-end gap-2"><a href="{{ $editing?route('health.profiles.show',$profile):route('health.profiles.index') }}" class="rounded-xl border border-slate-200 bg-white px-5 py-2.5 text-sm font-bold">انصراف</a><button class="rounded-xl bg-sky-600 px-6 py-2.5 text-sm font-bold text-white shadow-lg shadow-sky-200">{{ $editing?'ذخیره تغییرات':'ایجاد پرونده' }}</button></div></form>
@endsection
