@extends('layouts.app') @section('title','داشبورد') @section('page-title','داشبورد مدیریتی') @section('content')
<div class="mb-6 flex flex-col justify-between gap-3 sm:flex-row sm:items-center"><div><h2 class="text-xl font-black text-slate-900">سلام {{ str(auth()->user()->name)->before(' ') }}، وضعیت امروز سازمان</h2><p class="mt-1 text-sm text-slate-500">موارد مهم HSE که نیاز به توجه یا پیگیری دارند.</p></div><div class="flex gap-2"><a href="{{ route('incidents.create') }}" class="rounded-xl border border-slate-200 bg-white px-4 py-2.5 text-sm font-bold hover:border-rose-300 hover:text-rose-600">+ گزارش رویداد</a>@if(auth()->user()->hasRole(['admin','hse_manager','inspector']))<a href="{{ route('inspections.create') }}" class="rounded-xl bg-emerald-600 px-4 py-2.5 text-sm font-bold text-white shadow-lg shadow-emerald-200 hover:bg-emerald-700">+ بازرسی جدید</a>@endif</div></div>
<div class="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">
 @foreach([['اقدامات باز',$stats['open_actions'],'از کل اقدامات','bg-sky-500'],['سررسید گذشته',$stats['overdue_actions'],'نیازمند پیگیری فوری','bg-rose-500'],['ریسک زیاد و بحرانی',$stats['high_risks'],'ریسک کنترل‌نشده','bg-amber-500'],['رویدادهای ماه',$stats['incidents_month'],'حادثه و شبه‌حادثه','bg-violet-500']] as [$l,$v,$s,$c])<div class="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div class="flex items-start justify-between"><div><div class="text-sm text-slate-500">{{ $l }}</div><div class="mt-2 text-3xl font-black text-slate-900">{{ $v }}</div></div><div class="h-11 w-2 rounded-full {{ $c }}"></div></div><div class="mt-4 text-xs text-slate-400">{{ $s }}</div></div>@endforeach
</div>
<div class="mt-6 grid gap-6 xl:grid-cols-[1.6fr_1fr]">
 <section class="rounded-2xl border border-slate-200 bg-white shadow-sm"><div class="flex items-center justify-between border-b border-slate-100 p-5"><div><h3 class="font-black">اقدامات نیازمند پیگیری</h3><p class="text-xs text-slate-400">مرتب‌شده بر اساس سررسید</p></div><a href="{{ route('actions.index') }}" class="text-xs font-bold text-emerald-600">مشاهده همه ←</a></div><div class="overflow-x-auto"><table class="w-full min-w-[620px] text-right text-sm"><thead class="bg-slate-50 text-xs text-slate-500"><tr><th class="p-4">اقدام</th><th>مسئول</th><th>واحد</th><th>سررسید</th><th>وضعیت</th></tr></thead><tbody class="divide-y divide-slate-100">@forelse($actions as $a)<tr class="hover:bg-slate-50"><td class="p-4"><a class="font-bold text-slate-800 hover:text-emerald-600" href="{{ route('actions.show',$a) }}">{{ $a->title }}</a><div class="mt-1 text-[11px] text-slate-400">{{ $a->code }}</div></td><td>{{ $a->assignee->name }}</td><td>{{ $a->department->name }}</td><td class="{{ $a->is_overdue?'font-bold text-rose-600':'' }}">@jdate($a->due_date)</td><td><x-status :status="$a->status" /></td></tr>@empty<tr><td colspan="5" class="p-10 text-center text-slate-400">اقدام بازی وجود ندارد.</td></tr>@endforelse</tbody></table></div></section>
 <section class="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div class="mb-5 flex items-center justify-between"><h3 class="font-black">بازرسی‌های پیش‌رو</h3><a href="{{ route('inspections.index') }}" class="text-xs font-bold text-emerald-600">همه</a></div><div class="space-y-4">@forelse($upcomingInspections as $i)@php $jdt=\Morilog\Jalali\Jalalian::fromCarbon($i->scheduled_at); @endphp<a href="{{ route('inspections.show',$i) }}" class="flex gap-3 rounded-xl border border-slate-100 p-3 hover:border-emerald-200"><div class="grid h-12 w-12 shrink-0 place-items-center rounded-xl bg-emerald-50 text-center text-xs font-black text-emerald-700">{{ $jdt->getDay() }}<br>{{ $jdt->getMonth() }}</div><div class="min-w-0"><div class="truncate text-sm font-bold">{{ $i->title }}</div><div class="mt-1 text-xs text-slate-400">{{ $i->department->name }} · {{ $i->inspector->name }}</div></div></a>@empty<p class="py-10 text-center text-sm text-slate-400">بازرسی برنامه‌ریزی‌شده‌ای وجود ندارد.</p>@endforelse</div></section>
</div>
<div class="mt-6 grid gap-6 lg:grid-cols-2"><section class="rounded-2xl border border-slate-200 bg-white p-5"><h3 class="mb-4 font-black">آخرین ریسک‌های شناسایی‌شده</h3><div class="space-y-3">@foreach($recentRisks as $r)<a href="{{ route('risks.show',$r) }}" class="flex items-center gap-3 rounded-xl bg-slate-50 p-3"><div class="grid h-10 w-10 place-items-center rounded-xl {{ $r->risk_score>=17?'bg-rose-100 text-rose-700':($r->risk_score>=10?'bg-orange-100 text-orange-700':'bg-amber-100 text-amber-700') }} font-black">{{ $r->risk_score }}</div><div class="min-w-0 flex-1"><div class="truncate text-sm font-bold">{{ $r->title }}</div><div class="text-xs text-slate-400">{{ $r->department->name }}</div></div><span class="text-xs font-bold">{{ $r->risk_level }}</span></a>@endforeach</div></section><section class="rounded-2xl border border-slate-200 bg-white p-5"><h3 class="mb-4 font-black">فعالیت‌های اخیر سامانه</h3><div class="space-y-4">@foreach($activities as $a)<div class="flex gap-3"><div class="mt-1 h-2 w-2 shrink-0 rounded-full bg-emerald-500"></div><div><div class="text-sm"><b>{{ $a->user?->name ?? 'سیستم' }}</b> — {{ $a->description }}</div><div class="mt-1 text-[11px] text-slate-400">{{ $a->created_at->diffForHumans() }}</div></div></div>@endforeach</div></section></div>
@endsection
