<?php
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\{AuthController,ChecklistController,CorrectiveActionController,DashboardController,DepartmentController,IncidentController,InspectionController,ReportController,RiskController,SettingController,UserController};
Route::middleware('guest')->group(function(){Route::get('/login',[AuthController::class,'create'])->name('login');Route::post('/login',[AuthController::class,'store'])->name('login.store');});
Route::middleware('auth')->group(function(){
 Route::post('/logout',[AuthController::class,'destroy'])->name('logout'); Route::get('/',DashboardController::class)->name('dashboard');
 Route::middleware('role:admin,hse_manager,inspector')->group(function(){Route::get('inspections/create',[InspectionController::class,'create'])->name('inspections.create');Route::post('inspections',[InspectionController::class,'store'])->name('inspections.store');}); Route::resource('inspections',InspectionController::class)->only(['index','show']); Route::post('inspections/{inspection}/complete',[InspectionController::class,'complete'])->name('inspections.complete');
 Route::resource('risks',RiskController::class)->only(['index','create','store','show']); Route::resource('incidents',IncidentController::class)->only(['index','create','store','show']); Route::patch('incidents/{incident}/investigate',[IncidentController::class,'investigate'])->middleware('role:admin,hse_manager')->name('incidents.investigate');
 Route::middleware('role:admin,hse_manager')->group(function(){Route::get('actions/create',[CorrectiveActionController::class,'create'])->name('actions.create');Route::post('actions',[CorrectiveActionController::class,'store'])->name('actions.store');}); Route::resource('actions',CorrectiveActionController::class)->only(['index','show']); Route::post('actions/{action}/submit',[CorrectiveActionController::class,'submit'])->name('actions.submit'); Route::post('actions/{action}/verify',[CorrectiveActionController::class,'verify'])->middleware('role:admin,hse_manager')->name('actions.verify');
 Route::middleware('role:admin,hse_manager')->group(function(){Route::resource('checklists',ChecklistController::class)->only(['index','create','store']);Route::patch('checklists/{checklist}/toggle',[ChecklistController::class,'toggle'])->name('checklists.toggle');Route::get('reports',[ReportController::class,'index'])->name('reports.index');});
 Route::middleware('role:admin')->group(function(){Route::resource('users',UserController::class)->except(['show','destroy']);Route::patch('users/{user}/toggle',[UserController::class,'toggle'])->name('users.toggle');Route::resource('departments',DepartmentController::class)->only(['index','store','update']);Route::get('settings',[SettingController::class,'edit'])->name('settings.edit');Route::put('settings',[SettingController::class,'update'])->name('settings.update');});
});
