<?php
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\{AuthController,AiChatController,ChecklistController,ChecklistItemController,CorrectiveActionController,DashboardController,DepartmentController,IncidentController,InspectionController,NotificationController,PpeController,ReportController,RiskController,RiskMethodController,SafetyEquipmentController,SettingController,UserController,WorkPermitController};
Route::middleware('guest')->group(function(){Route::get('/login',[AuthController::class,'create'])->name('login');Route::post('/login',[AuthController::class,'store'])->name('login.store');});
Route::middleware('auth')->group(function(){
 Route::post('/logout',[AuthController::class,'destroy'])->name('logout'); Route::get('/',DashboardController::class)->name('dashboard');
 Route::middleware('role:admin,hse_manager,inspector')->group(function(){Route::get('inspections/create',[InspectionController::class,'create'])->name('inspections.create');Route::post('inspections',[InspectionController::class,'store'])->name('inspections.store');}); Route::resource('inspections',InspectionController::class)->only(['index','show']); Route::post('inspections/{inspection}/complete',[InspectionController::class,'complete'])->name('inspections.complete');
 Route::resource('risks',RiskController::class)->only(['index','create','store','show']); Route::resource('incidents',IncidentController::class)->only(['index','create','store','show']); Route::patch('incidents/{incident}/investigate',[IncidentController::class,'investigate'])->middleware('role:admin,hse_manager')->name('incidents.investigate');
 Route::middleware('role:admin,hse_manager,inspector')->group(function(){Route::get('risks/{risk}/jsa/create',[RiskMethodController::class,'createJsa'])->name('risks.jsa.create');Route::post('risks/{risk}/jsa',[RiskMethodController::class,'storeJsa'])->name('risks.jsa.store');Route::get('risks/{risk}/fmea/create',[RiskMethodController::class,'createFmea'])->name('risks.fmea.create');Route::post('risks/{risk}/fmea',[RiskMethodController::class,'storeFmea'])->name('risks.fmea.store');Route::post('fmea/{fmea}/actions',[RiskMethodController::class,'createActionFromFmea'])->name('fmea.actions.store');});
 Route::middleware('role:admin,hse_manager')->group(function(){Route::get('actions/create',[CorrectiveActionController::class,'create'])->name('actions.create');Route::post('actions',[CorrectiveActionController::class,'store'])->name('actions.store');}); Route::resource('actions',CorrectiveActionController::class)->only(['index','show']); Route::post('actions/{action}/start',[CorrectiveActionController::class,'start'])->name('actions.start'); Route::post('actions/{action}/submit',[CorrectiveActionController::class,'submit'])->name('actions.submit'); Route::post('actions/{action}/verify',[CorrectiveActionController::class,'verify'])->middleware('role:admin,hse_manager')->name('actions.verify'); Route::post('actions/{action}/close',[CorrectiveActionController::class,'close'])->middleware('role:admin,hse_manager')->name('actions.close');
 Route::get('notifications',[NotificationController::class,'index'])->name('notifications.index');Route::get('notifications/poll',[NotificationController::class,'poll'])->name('notifications.poll');Route::post('notifications/{notification}/read',[NotificationController::class,'read'])->name('notifications.read');
 Route::get('ppe',[PpeController::class,'index'])->name('ppe.index');Route::middleware('role:admin,hse_manager')->group(function(){Route::post('ppe/types',[PpeController::class,'storeType'])->name('ppe.types.store');Route::post('ppe/requirements',[PpeController::class,'storeRequirement'])->name('ppe.requirements.store');Route::post('ppe/issues',[PpeController::class,'storeIssue'])->name('ppe.issues.store');});
 Route::get('equipment',[SafetyEquipmentController::class,'index'])->name('equipment.index');Route::middleware('role:admin,hse_manager')->group(function(){Route::post('equipment',[SafetyEquipmentController::class,'store'])->name('equipment.store');Route::post('equipment/{equipment}/inspect',[SafetyEquipmentController::class,'inspect'])->name('equipment.inspect');});
 Route::resource('permits',WorkPermitController::class)->only(['index','create','store','show']);Route::post('permits/{permit}/transition',[WorkPermitController::class,'transition'])->name('permits.transition');
 Route::middleware('role:admin,hse_manager')->group(function(){Route::resource('checklists',ChecklistController::class)->except(['show']);Route::get('checklists/{checklist}',[ChecklistController::class,'show'])->name('checklists.show');Route::patch('checklists/{checklist}/toggle',[ChecklistController::class,'toggle'])->name('checklists.toggle');Route::resource('checklists.items',ChecklistItemController::class)->only(['create','store','edit','update','destroy']);Route::patch('checklists/{checklist}/items/{item}/toggle',[ChecklistItemController::class,'toggle'])->name('checklists.items.toggle');Route::patch('checklists/{checklist}/items/{item}/move',[ChecklistItemController::class,'move'])->name('checklists.items.move');Route::get('reports',[ReportController::class,'index'])->name('reports.index');Route::get('reports/export',[ReportController::class,'export'])->name('reports.export');});
 Route::middleware('role:admin')->group(function(){Route::resource('users',UserController::class)->except(['show','destroy']);Route::patch('users/{user}/toggle',[UserController::class,'toggle'])->name('users.toggle');Route::resource('departments',DepartmentController::class)->only(['index','store','update']);Route::get('settings',[SettingController::class,'edit'])->name('settings.edit');Route::put('settings',[SettingController::class,'update'])->name('settings.update');});
 Route::post('/ai/chat',[AiChatController::class,'chat'])->name('ai.chat');
 Route::post('/ai/action',[AiChatController::class,'executeAction'])->name('ai.action');
 Route::get('/ai/conversations',[AiChatController::class,'conversations'])->name('ai.conversations');
 Route::post('/ai/conversations',[AiChatController::class,'newConversation'])->name('ai.conversations.new');
 Route::post('/ai/conversations/force-new',[AiChatController::class,'forceNewConversation'])->name('ai.conversations.forceNew');
 Route::get('/ai/conversations/{id}',[AiChatController::class,'showConversation'])->name('ai.conversations.show');
 Route::delete('/ai/conversations/{id}',[AiChatController::class,'deleteConversation'])->name('ai.conversations.delete');
 Route::delete('/ai/conversations',[AiChatController::class,'deleteAllConversations'])->name('ai.conversations.deleteAll');
});
