 <?php $__env->startSection('title','داشبورد'); ?> <?php $__env->startSection('page-title','داشبورد مدیریتی'); ?> <?php $__env->startSection('content'); ?>
<div class="mb-6 flex flex-col justify-between gap-3 sm:flex-row sm:items-center"><div><h2 class="text-xl font-black text-slate-900">سلام <?php echo e(str(auth()->user()->name)->before(' ')); ?>، وضعیت امروز سازمان</h2><p class="mt-1 text-sm text-slate-500">موارد مهم HSE که نیاز به توجه یا پیگیری دارند.</p></div><div class="flex gap-2"><a href="<?php echo e(route('incidents.create')); ?>" class="rounded-xl border border-slate-200 bg-white px-4 py-2.5 text-sm font-bold hover:border-rose-300 hover:text-rose-600">+ گزارش رویداد</a><?php if(auth()->user()->hasRole(['admin','hse_manager','inspector'])): ?><a href="<?php echo e(route('inspections.create')); ?>" class="rounded-xl bg-emerald-600 px-4 py-2.5 text-sm font-bold text-white shadow-lg shadow-emerald-200 hover:bg-emerald-700">+ بازرسی جدید</a><?php endif; ?></div></div>
<div class="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">
 <?php $__currentLoopData = [['اقدامات باز',$stats['open_actions'],'از کل اقدامات','bg-sky-500'],['سررسید گذشته',$stats['overdue_actions'],'نیازمند پیگیری فوری','bg-rose-500'],['ریسک زیاد و بحرانی',$stats['high_risks'],'ریسک کنترل‌نشده','bg-amber-500'],['رویدادهای ماه',$stats['incidents_month'],'حادثه و شبه‌حادثه','bg-violet-500']]; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as [$l,$v,$s,$c]): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><div class="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div class="flex items-start justify-between"><div><div class="text-sm text-slate-500"><?php echo e($l); ?></div><div class="mt-2 text-3xl font-black text-slate-900"><?php echo e($v); ?></div></div><div class="h-11 w-2 rounded-full <?php echo e($c); ?>"></div></div><div class="mt-4 text-xs text-slate-400"><?php echo e($s); ?></div></div><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?>
</div>
<div class="mt-6 grid gap-6 xl:grid-cols-[1.6fr_1fr]">
 <section class="rounded-2xl border border-slate-200 bg-white shadow-sm"><div class="flex items-center justify-between border-b border-slate-100 p-5"><div><h3 class="font-black">اقدامات نیازمند پیگیری</h3><p class="text-xs text-slate-400">مرتب‌شده بر اساس سررسید</p></div><a href="<?php echo e(route('actions.index')); ?>" class="text-xs font-bold text-emerald-600">مشاهده همه ←</a></div><div class="overflow-x-auto"><table class="w-full min-w-[620px] text-right text-sm"><thead class="bg-slate-50 text-xs text-slate-500"><tr><th class="p-4">اقدام</th><th>مسئول</th><th>واحد</th><th>سررسید</th><th>وضعیت</th></tr></thead><tbody class="divide-y divide-slate-100"><?php $__empty_1 = true; $__currentLoopData = $actions; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $a): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); $__empty_1 = false; ?><tr class="hover:bg-slate-50"><td class="p-4"><a class="font-bold text-slate-800 hover:text-emerald-600" href="<?php echo e(route('actions.show',$a)); ?>"><?php echo e($a->title); ?></a><div class="mt-1 text-[11px] text-slate-400"><?php echo e($a->code); ?></div></td><td><?php echo e($a->assignee->name); ?></td><td><?php echo e($a->department->name); ?></td><td class="<?php echo e($a->is_overdue?'font-bold text-rose-600':''); ?>"><?php echo \Morilog\Jalali\Jalalian::fromCarbon($a->due_date)->format('Y/m/d'); ?></td><td><?php if (isset($component)) { $__componentOriginal51ed764111e345fc11534f121cfeb451 = $component; } ?>
<?php if (isset($attributes)) { $__attributesOriginal51ed764111e345fc11534f121cfeb451 = $attributes; } ?>
<?php $component = Illuminate\View\AnonymousComponent::resolve(['view' => 'components.status','data' => ['status' => $a->status]] + (isset($attributes) && $attributes instanceof Illuminate\View\ComponentAttributeBag ? $attributes->all() : [])); ?>
<?php $component->withName('status'); ?>
<?php if ($component->shouldRender()): ?>
<?php $__env->startComponent($component->resolveView(), $component->data()); ?>
<?php if (isset($attributes) && $attributes instanceof Illuminate\View\ComponentAttributeBag): ?>
<?php $attributes = $attributes->except(\Illuminate\View\AnonymousComponent::ignoredParameterNames()); ?>
<?php endif; ?>
<?php $component->withAttributes(['status' => \Illuminate\View\Compilers\BladeCompiler::sanitizeComponentAttribute($a->status)]); ?>
<?php echo $__env->renderComponent(); ?>
<?php endif; ?>
<?php if (isset($__attributesOriginal51ed764111e345fc11534f121cfeb451)): ?>
<?php $attributes = $__attributesOriginal51ed764111e345fc11534f121cfeb451; ?>
<?php unset($__attributesOriginal51ed764111e345fc11534f121cfeb451); ?>
<?php endif; ?>
<?php if (isset($__componentOriginal51ed764111e345fc11534f121cfeb451)): ?>
<?php $component = $__componentOriginal51ed764111e345fc11534f121cfeb451; ?>
<?php unset($__componentOriginal51ed764111e345fc11534f121cfeb451); ?>
<?php endif; ?></td></tr><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); if ($__empty_1): ?><tr><td colspan="5" class="p-10 text-center text-slate-400">اقدام بازی وجود ندارد.</td></tr><?php endif; ?></tbody></table></div></section>
 <section class="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div class="mb-5 flex items-center justify-between"><h3 class="font-black">بازرسی‌های پیش‌رو</h3><a href="<?php echo e(route('inspections.index')); ?>" class="text-xs font-bold text-emerald-600">همه</a></div><div class="space-y-4"><?php $__empty_1 = true; $__currentLoopData = $upcomingInspections; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $i): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); $__empty_1 = false; ?><?php $jdt=\Morilog\Jalali\Jalalian::fromCarbon($i->scheduled_at); ?><a href="<?php echo e(route('inspections.show',$i)); ?>" class="flex gap-3 rounded-xl border border-slate-100 p-3 hover:border-emerald-200"><div class="grid h-12 w-12 shrink-0 place-items-center rounded-xl bg-emerald-50 text-center text-xs font-black text-emerald-700"><?php echo e($jdt->getDay()); ?><br><?php echo e($jdt->getMonth()); ?></div><div class="min-w-0"><div class="truncate text-sm font-bold"><?php echo e($i->title); ?></div><div class="mt-1 text-xs text-slate-400"><?php echo e($i->department->name); ?> · <?php echo e($i->inspector->name); ?></div></div></a><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); if ($__empty_1): ?><p class="py-10 text-center text-sm text-slate-400">بازرسی برنامه‌ریزی‌شده‌ای وجود ندارد.</p><?php endif; ?></div></section>
</div>
<div class="mt-6 grid gap-6 lg:grid-cols-2"><section class="rounded-2xl border border-slate-200 bg-white p-5"><h3 class="mb-4 font-black">آخرین ریسک‌های شناسایی‌شده</h3><div class="space-y-3"><?php $__currentLoopData = $recentRisks; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $r): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><a href="<?php echo e(route('risks.show',$r)); ?>" class="flex items-center gap-3 rounded-xl bg-slate-50 p-3"><div class="grid h-10 w-10 place-items-center rounded-xl <?php echo e($r->risk_score>=17?'bg-rose-100 text-rose-700':($r->risk_score>=10?'bg-orange-100 text-orange-700':'bg-amber-100 text-amber-700')); ?> font-black"><?php echo e($r->risk_score); ?></div><div class="min-w-0 flex-1"><div class="truncate text-sm font-bold"><?php echo e($r->title); ?></div><div class="text-xs text-slate-400"><?php echo e($r->department->name); ?></div></div><span class="text-xs font-bold"><?php echo e($r->risk_level); ?></span></a><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?></div></section><section class="rounded-2xl border border-slate-200 bg-white p-5"><h3 class="mb-4 font-black">فعالیت‌های اخیر سامانه</h3><div class="space-y-4"><?php $__currentLoopData = $activities; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $a): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><div class="flex gap-3"><div class="mt-1 h-2 w-2 shrink-0 rounded-full bg-emerald-500"></div><div><div class="text-sm"><b><?php echo e($a->user?->name ?? 'سیستم'); ?></b> — <?php echo e($a->description); ?></div><div class="mt-1 text-[11px] text-slate-400"><?php echo e($a->created_at->diffForHumans()); ?></div></div></div><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?></div></section></div>
<?php $__env->stopSection(); ?>

<?php echo $__env->make('layouts.app', array_diff_key(get_defined_vars(), ['__data' => 1, '__path' => 1]))->render(); ?><?php /**PATH E:\HSE\hse-manager\resources\views/dashboard/index.blade.php ENDPATH**/ ?>