 <?php $__env->startSection('title','بازرسی جدید'); ?> <?php $__env->startSection('page-title','برنامه‌ریزی بازرسی'); ?> <?php $__env->startSection('content'); ?>
<form method="post" action="<?php echo e(route('inspections.store')); ?>" class="mx-auto max-w-4xl"><?php echo csrf_field(); ?><div class="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><div class="mb-6 border-b border-slate-100 pb-4"><h2 class="font-black">مشخصات بازرسی</h2><p class="mt-1 text-xs text-slate-400">چک‌لیست، واحد و بازرس مسئول را مشخص کنید.</p></div><div class="grid gap-5 md:grid-cols-2">
<?php echo $__env->make('components.field',['label'=>'عنوان بازرسی','name'=>'title','placeholder'=>'مثلاً بازرسی دوره‌ای کارگاه تولید'], array_diff_key(get_defined_vars(), ['__data' => 1, '__path' => 1]))->render(); ?>
<label class="block"><span class="mb-2 block text-sm font-bold">چک‌لیست *</span><select name="checklist_id" required class="w-full rounded-xl border border-slate-200 bg-slate-50 px-4 py-3"><option value="">انتخاب کنید</option><?php $__currentLoopData = $checklists; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $c): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><option value="<?php echo e($c->id); ?>"><?php echo e($c->title); ?> — نسخه <?php echo e($c->version); ?></option><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?></select></label>
<label class="block"><span class="mb-2 block text-sm font-bold">واحد سازمانی *</span><select name="department_id" required class="w-full rounded-xl border border-slate-200 bg-slate-50 px-4 py-3"><option value="">انتخاب کنید</option><?php $__currentLoopData = $departments; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $d): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><option value="<?php echo e($d->id); ?>"><?php echo e($d->name); ?></option><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?></select></label>
<label class="block"><span class="mb-2 block text-sm font-bold">بازرس مسئول *</span><select name="inspector_id" required class="w-full rounded-xl border border-slate-200 bg-slate-50 px-4 py-3"><option value="">انتخاب کنید</option><?php $__currentLoopData = $inspectors; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $u): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><option value="<?php echo e($u->id); ?>"><?php echo e($u->name); ?></option><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?></select></label>
<?php echo $__env->make('components.field',['label'=>'تاریخ و ساعت برنامه','name'=>'scheduled_at','type'=>'datetime-local'], array_diff_key(get_defined_vars(), ['__data' => 1, '__path' => 1]))->render(); ?> <?php echo $__env->make('components.field',['label'=>'محل دقیق بازرسی','name'=>'location','placeholder'=>'ساختمان / سالن / خط تولید'], array_diff_key(get_defined_vars(), ['__data' => 1, '__path' => 1]))->render(); ?>
</div></div><div class="mt-5 flex justify-end gap-3"><a href="<?php echo e(route('inspections.index')); ?>" class="rounded-xl border border-slate-200 px-5 py-3 text-sm font-bold hover:bg-slate-50">انصراف</a><button class="rounded-xl bg-emerald-600 px-6 py-3 text-sm font-black text-white">ثبت برنامه بازرسی</button></div></form><?php $__env->stopSection(); ?>

<?php echo $__env->make('layouts.app', array_diff_key(get_defined_vars(), ['__data' => 1, '__path' => 1]))->render(); ?><?php /**PATH E:\HSE\hse-manager\resources\views/inspections/create.blade.php ENDPATH**/ ?>