 <?php $__env->startSection('title','اقدامات اصلاحی'); ?> <?php $__env->startSection('page-title','اقدامات اصلاحی'); ?> <?php $__env->startSection('content'); ?>
<div class="mb-5 flex items-center justify-between"><div><h2 class="text-xl font-black">پیگیری اقدامات</h2><p class="mt-1 text-sm text-slate-500">از ارجاع تا اجرا و تأیید اثربخشی</p></div><?php if(auth()->user()->hasRole(['admin','hse_manager'])): ?><a href="<?php echo e(route('actions.create')); ?>" class="rounded-xl bg-emerald-600 px-4 py-3 text-sm font-bold text-white hover:bg-emerald-700">+ اقدام جدید</a><?php endif; ?></div><div class="mb-4 flex flex-wrap gap-2"><?php $__currentLoopData = [''=>'همه','assigned'=>'ارجاع‌شده','pending_verification'=>'منتظر تأیید','rejected'=>'عودت‌شده','verified'=>'تأییدشده']; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $v=>$l): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><a href="<?php echo e(route('actions.index',['status'=>$v])); ?>" class="rounded-xl border px-4 py-2 text-xs font-bold <?php echo e(request('status','')===$v?'border-slate-900 bg-slate-900 text-white':'border-slate-200 bg-white'); ?>"><?php echo e($l); ?></a><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?></div><div class="overflow-hidden rounded-2xl border border-slate-200 bg-white"><div class="overflow-x-auto"><table class="w-full min-w-[850px] text-right text-sm"><thead class="bg-slate-50 text-xs text-slate-500"><tr><th class="p-4">اقدام</th><th>واحد</th><th>مسئول</th><th>اولویت</th><th>سررسید</th><th>وضعیت</th></tr></thead><tbody class="divide-y"><?php $__empty_1 = true; $__currentLoopData = $actions; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $a): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); $__empty_1 = false; ?><tr class="<?php echo e($a->is_overdue?'bg-rose-50/50':''); ?>"><td class="p-4"><a href="<?php echo e(route('actions.show',$a)); ?>" class="font-bold hover:text-emerald-600"><?php echo e($a->title); ?></a><div class="text-[11px] text-slate-400"><?php echo e($a->code); ?></div></td><td><?php echo e($a->department->name); ?></td><td><?php echo e($a->assignee->name); ?></td><td><?php echo e(['low'=>'کم','medium'=>'متوسط','high'=>'زیاد','critical'=>'فوری'][$a->priority]); ?></td><td class="<?php echo e($a->is_overdue?'font-black text-rose-600':''); ?>"><?php echo \Morilog\Jalali\Jalalian::fromCarbon($a->due_date)->format('Y/m/d'); ?> <?php if($a->is_overdue): ?><small>(گذشته)</small><?php endif; ?></td><td><?php if (isset($component)) { $__componentOriginal51ed764111e345fc11534f121cfeb451 = $component; } ?>
<?php if (isset($attributes)) { $__attributesOriginal51ed764111e345fc11534f121cfeb451 = $attributes; } ?>
<?php $component = Illuminate\View\AnonymousComponent::resolve(['view' => 'components.status','data' => ['status' => $a->status]] + (isset($attributes) && $attributes instanceof Illuminate\View\ComponentAttributeBag ? $attributes->all() : [])); ?>
<?php $component->withName('status'); ?>
<?php if ($component->shouldRender()): ?>
<?php $__env->startComponent($component->resolveView(), $component->data()); ?>
<?php if (isset($attributes) && $attributes instanceof Illuminate\View\ComponentAttributeBag): ?>
<?php $attributes = $attributes->except(\Illuminate\View\AnonymousComponent::ignoredParameterNames()); ?>
<?php endif; ?>
<?php $component->withAttributes(['status' => \Illuminate\View\Compilers\BladeCompiler::sanitizeComponentAttribute($a->status)]); ?>
<?php echo $__env->renderComponent(); ?>
<?php endif; ?>
<?php if (isset($__attributesOriginal51ed764111e345fc11534f121cfeb451)): ?>
<?php $attributes = $__attributesOriginal51ed764111e345fc11534f121cfeb451; ?>
<?php unset($__attributesOriginal51ed764111e345fc11534f121cfeb451); ?>
<?php endif; ?>
<?php if (isset($__componentOriginal51ed764111e345fc11534f121cfeb451)): ?>
<?php $component = $__componentOriginal51ed764111e345fc11534f121cfeb451; ?>
<?php unset($__componentOriginal51ed764111e345fc11534f121cfeb451); ?>
<?php endif; ?></td></tr><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); if ($__empty_1): ?><tr><td colspan="6" class="p-12 text-center text-slate-400">اقدامی یافت نشد.</td></tr><?php endif; ?></tbody></table></div><div class="border-t p-4"><?php echo e($actions->links()); ?></div></div><?php $__env->stopSection(); ?>

<?php echo $__env->make('layouts.app', array_diff_key(get_defined_vars(), ['__data' => 1, '__path' => 1]))->render(); ?><?php /**PATH E:\HSE\hse-manager\resources\views/actions/index.blade.php ENDPATH**/ ?>