<!doctype html><html lang="fa" dir="rtl"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="csrf-token" content="<?php echo e(csrf_token()); ?>"><title><?php echo $__env->yieldContent('title','داشبورد'); ?> | HSE</title><?php echo app('Illuminate\Foundation\Vite')(['resources/css/app.css','resources/js/app.js']); ?><link rel="stylesheet" href="https://unpkg.com/persian-datepicker@1.2.0/dist/css/persian-datepicker.min.css"><script src="https://unpkg.com/jquery@3.7.1/dist/jquery.min.js"></script><script src="https://unpkg.com/persian-date@1.1.0/dist/persian-date.min.js"></script><script src="https://unpkg.com/persian-datepicker@1.2.0/dist/js/persian-datepicker.min.js"></script><style>.datepicker-plot-area{font-family:-apple-system,"Segoe UI",system-ui,sans-serif!important;border-radius:1rem!important;border:1px solid #e5e7eb!important;box-shadow:0 10px 40px #0001!important;} .datepicker-plot-area *{direction:rtl!important;} .selected-day{background:#10b981!important;} .hover{background:#d1fae5!important;color:#065f46!important;}</style></head>
<body class="min-h-screen bg-slate-50 text-slate-800 antialiased">
<div class="min-h-screen lg:grid lg:grid-cols-[270px_1fr]">
 <aside class="hidden lg:flex sticky top-0 h-screen flex-col bg-slate-950 text-white">
  <div class="flex h-20 items-center gap-3 border-b border-white/10 px-6"><div class="grid h-11 w-11 place-items-center rounded-2xl bg-gradient-to-br from-emerald-400 to-teal-600 shadow-lg shadow-emerald-950/40"><svg class="h-6 w-6" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-width="2" d="M12 3l8 4v5c0 5-3.5 8-8 9-4.5-1-8-4-8-9V7l8-4zM9 12l2 2 4-5"/></svg></div><div><div class="font-black">سامانه مدیریت HSE</div><div class="mt-0.5 text-[11px] text-slate-400">سلامت، ایمنی و محیط‌زیست</div></div></div>
  <nav class="scrollbar-thin flex-1 space-y-1 overflow-y-auto p-4 text-sm">
   <?php $nav=[['dashboard','داشبورد','home'],['inspections.index','بازرسی‌ها','clipboard'],['risks.index','خطرات و ریسک‌ها','warning'],['incidents.index','حوادث و شبه‌حوادث','incident'],['actions.index','اقدامات اصلاحی','check']]; ?>
   <?php $__currentLoopData = $nav; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as [$route,$label,$icon]): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?> <a href="<?php echo e(route($route)); ?>" class="flex items-center gap-3 rounded-xl px-3 py-3 transition <?php echo e(request()->routeIs(str($route)->before('.').'.*')||request()->routeIs($route)?'bg-emerald-500 font-bold text-white shadow-lg shadow-emerald-950/30':'text-slate-300 hover:bg-white/5 hover:text-white'); ?>"><span class="grid h-8 w-8 place-items-center rounded-lg bg-white/10"><?php echo $__env->make('components.icon',['name'=>$icon], array_diff_key(get_defined_vars(), ['__data' => 1, '__path' => 1]))->render(); ?></span><?php echo e($label); ?></a><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?>
   <?php if(auth()->user()->hasRole(['admin','hse_manager'])): ?><div class="px-3 pb-1 pt-5 text-[10px] font-bold tracking-widest text-slate-500">مدیریت و تحلیل</div><a href="<?php echo e(route('checklists.index')); ?>" class="flex items-center gap-3 rounded-xl px-3 py-3 text-slate-300 hover:bg-white/5 hover:text-white"><?php echo $__env->make('components.icon',['name'=>'list'], array_diff_key(get_defined_vars(), ['__data' => 1, '__path' => 1]))->render(); ?> چک‌لیست‌ها</a><a href="<?php echo e(route('reports.index')); ?>" class="flex items-center gap-3 rounded-xl px-3 py-3 text-slate-300 hover:bg-white/5 hover:text-white"><?php echo $__env->make('components.icon',['name'=>'chart'], array_diff_key(get_defined_vars(), ['__data' => 1, '__path' => 1]))->render(); ?> گزارش‌های مدیریتی</a><?php endif; ?>
   <?php if(auth()->user()->hasRole('admin')): ?><a href="<?php echo e(route('users.index')); ?>" class="flex items-center gap-3 rounded-xl px-3 py-3 text-slate-300 hover:bg-white/5 hover:text-white"><?php echo $__env->make('components.icon',['name'=>'users'], array_diff_key(get_defined_vars(), ['__data' => 1, '__path' => 1]))->render(); ?> کاربران و دسترسی‌ها</a><a href="<?php echo e(route('departments.index')); ?>" class="flex items-center gap-3 rounded-xl px-3 py-3 text-slate-300 hover:bg-white/5 hover:text-white"><?php echo $__env->make('components.icon',['name'=>'building'], array_diff_key(get_defined_vars(), ['__data' => 1, '__path' => 1]))->render(); ?> واحدهای سازمانی</a><a href="<?php echo e(route('settings.edit')); ?>" class="flex items-center gap-3 rounded-xl px-3 py-3 text-slate-300 hover:bg-white/5 hover:text-white"><?php echo $__env->make('components.icon',['name'=>'settings'], array_diff_key(get_defined_vars(), ['__data' => 1, '__path' => 1]))->render(); ?> تنظیمات سامانه</a><?php endif; ?>
  </nav>
  <div class="m-4 rounded-2xl border border-white/10 bg-white/5 p-3"><div class="flex items-center gap-3"><div class="grid h-10 w-10 place-items-center rounded-xl bg-emerald-500 font-black"><?php echo e(mb_substr(auth()->user()->name,0,1)); ?></div><div class="min-w-0 flex-1"><div class="truncate text-sm font-bold"><?php echo e(auth()->user()->name); ?></div><div class="truncate text-[11px] text-slate-400"><?php echo e(auth()->user()->role->label()); ?></div></div><form method="post" action="<?php echo e(route('logout')); ?>"><?php echo csrf_field(); ?><button class="rounded-lg p-2 text-slate-400 hover:bg-white/10 hover:text-white" title="خروج"><?php echo $__env->make('components.icon',['name'=>'logout'], array_diff_key(get_defined_vars(), ['__data' => 1, '__path' => 1]))->render(); ?></button></form></div></div>
 </aside>
 <main class="min-w-0">
  <header class="sticky top-0 z-30 flex h-16 items-center justify-between border-b border-slate-200/80 bg-white/90 px-4 backdrop-blur lg:px-8"><div><div class="text-xs text-slate-400">امروز، <?php echo e(\Morilog\Jalali\Jalalian::now()->format('l d F Y')); ?></div><h1 class="font-black text-slate-900"><?php echo $__env->yieldContent('page-title','داشبورد'); ?></h1></div><div class="flex items-center gap-2"><a href="<?php echo e(route('actions.index',['status'=>'assigned'])); ?>" title="اقدامات اصلاحی" class="relative grid h-10 w-10 place-items-center rounded-xl border border-slate-200 bg-white text-slate-500 hover:border-emerald-300 hover:text-emerald-600"><?php echo $__env->make('components.icon',['name'=>'bell'], array_diff_key(get_defined_vars(), ['__data' => 1, '__path' => 1]))->render(); ?></a><div class="lg:hidden rounded-xl bg-slate-900 px-3 py-2 text-xs font-bold text-white">HSE</div></div></header>
  <div class="p-4 pb-24 lg:p-8">
   <?php if(session('success')): ?><div data-auto-dismiss class="mb-5 flex items-center gap-3 rounded-2xl border border-emerald-200 bg-emerald-50 px-4 py-3 text-sm font-bold text-emerald-800"><?php echo $__env->make('components.icon',['name'=>'check'], array_diff_key(get_defined_vars(), ['__data' => 1, '__path' => 1]))->render(); ?> <?php echo e(session('success')); ?></div><?php endif; ?>
   <?php if($errors->any()): ?><div class="mb-5 rounded-2xl border border-rose-200 bg-rose-50 p-4 text-sm text-rose-800"><div class="mb-2 font-black">لطفاً موارد زیر را اصلاح کنید:</div><ul class="list-inside list-disc space-y-1"><?php $__currentLoopData = $errors->all(); $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $e): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><li><?php echo e($e); ?></li><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?></ul></div><?php endif; ?>
   <?php echo $__env->yieldContent('content'); ?>
  </div>
 </main>
 <nav class="fixed inset-x-3 bottom-3 z-40 flex items-center justify-around rounded-2xl border border-slate-200 bg-white/95 p-2 shadow-2xl backdrop-blur lg:hidden"><?php $__currentLoopData = [['dashboard','home','خانه'],['inspections.index','clipboard','بازرسی'],['risks.index','warning','ریسک'],['incidents.index','incident','رویداد'],['actions.index','check','اقدامات']]; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as [$route,$icon,$label]): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><a href="<?php echo e(route($route)); ?>" class="flex min-w-14 flex-col items-center gap-1 rounded-xl px-2 py-1.5 text-[10px] font-bold <?php echo e(request()->routeIs(str($route)->before('.').'.*')||request()->routeIs($route)?'bg-emerald-50 text-emerald-700':'text-slate-400'); ?>"><?php echo $__env->make('components.icon',['name'=>$icon], array_diff_key(get_defined_vars(), ['__data' => 1, '__path' => 1]))->render(); ?><?php echo e($label); ?></a><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?></nav>
</div>
<script>
$(function(){
  $('[data-jdatepicker]').each(function(){
    var isDatetime = $(this).data('jdatepicker') === 'datetime';
    $(this).persianDatepicker({
      format: isDatetime ? 'YYYY/MM/DD HH:mm' : 'YYYY/MM/DD',
      altFormat: isDatetime ? 'YYYY-MM-DD HH:mm:ss' : 'YYYY-MM-DD',
      timePicker: { enabled: isDatetime, meridian: { enabled: false } },
      calendar: { persian: { locale: 'fa' } },
      initialValue: true,
      observer: true,
      position: 'auto'
    });
  });
});
</script>
</body></html>
<?php /**PATH E:\HSE\hse-manager\resources\views/layouts/app.blade.php ENDPATH**/ ?>