@extends('layouts.app') @section('title','گزارش‌ها') @section('page-title','گزارش‌های مدیریتی HSE') @section('content')
@php
    $jFrom  = \Morilog\Jalali\Jalalian::fromCarbon($from);
    $jTo    = \Morilog\Jalali\Jalalian::fromCarbon($to);
    $fromVal = $jFrom->getYear() . '/' . sprintf('%02d', $jFrom->getMonth()) . '/' . sprintf('%02d', $jFrom->getDay());
    $toVal   = $jTo->getYear()   . '/' . sprintf('%02d', $jTo->getMonth())   . '/' . sprintf('%02d', $jTo->getDay());
    $riskChart = ['type' => 'doughnut', 'data' => ['labels' => ['بحرانی', 'زیاد', 'متوسط', 'کم'], 'datasets' => [['data' => [$riskByLevel['بحرانی'] ?? 0, $riskByLevel['زیاد'] ?? 0, $riskByLevel['متوسط'] ?? 0, $riskByLevel['کم'] ?? 0], 'backgroundColor' => ['#e11d48', '#f97316', '#f59e0b', '#10b981'], 'borderWidth' => 0]]], 'options' => ['responsive' => true, 'maintainAspectRatio' => false, 'plugins' => ['legend' => ['position' => 'bottom', 'rtl' => true, 'labels' => ['usePointStyle' => true, 'padding' => 18]]]]];
    $incidentChart = ['type' => 'bar', 'data' => ['labels' => ['حادثه', 'شبه‌حادثه', 'بیماری شغلی', 'محیط‌زیستی'], 'datasets' => [['label' => 'تعداد رویداد', 'data' => [$incidentByType['incident'] ?? 0, $incidentByType['near_miss'] ?? 0, $incidentByType['occupational_disease'] ?? 0, $incidentByType['environmental'] ?? 0], 'backgroundColor' => ['#f43f5e', '#f59e0b', '#8b5cf6', '#0ea5e9'], 'borderRadius' => 8, 'borderSkipped' => false]]], 'options' => ['responsive' => true, 'maintainAspectRatio' => false, 'plugins' => ['legend' => ['display' => false]], 'scales' => ['y' => ['beginAtZero' => true, 'ticks' => ['precision' => 0]], 'x' => ['grid' => ['display' => false]]]]];
    $departmentLabels = $departmentStats->pluck('name')->values()->all();
    $departmentRisks = $departmentStats->pluck('risks_count')->map(fn($value) => (int) $value)->values()->all();
    $departmentActions = $departmentStats->pluck('actions_open')->map(fn($value) => (int) $value)->values()->all();
    $departmentInspections = $departmentStats->pluck('inspection_avg')->map(fn($value) => (float) $value)->values()->all();
    $departmentChart = ['type' => 'bar', 'data' => ['labels' => $departmentLabels, 'datasets' => [['label' => 'ریسک ثبت‌شده', 'data' => $departmentRisks, 'backgroundColor' => '#f97316', 'borderRadius' => 6, 'borderSkipped' => false, 'barThickness' => 10, 'maxBarThickness' => 12], ['label' => 'اقدام باز', 'data' => $departmentActions, 'backgroundColor' => '#0ea5e9', 'borderRadius' => 6, 'borderSkipped' => false, 'barThickness' => 10, 'maxBarThickness' => 12], ['label' => 'میانگین بازرسی', 'data' => $departmentInspections, 'backgroundColor' => '#10b981', 'borderRadius' => 6, 'borderSkipped' => false, 'barThickness' => 10, 'maxBarThickness' => 12]]], 'options' => ['responsive' => true, 'maintainAspectRatio' => false, 'plugins' => ['legend' => ['position' => 'bottom', 'rtl' => true, 'labels' => ['usePointStyle' => true, 'padding' => 18]]], 'scales' => ['y' => ['beginAtZero' => true, 'ticks' => ['precision' => 0]], 'x' => ['grid' => ['display' => false], 'categoryPercentage' => .65, 'barPercentage' => .7]]]];
@endphp
<div class="mb-4 flex flex-wrap gap-2"><span class="py-2 text-sm font-bold">خروجی Excel/CSV:</span>@foreach(['risks'=>'ریسک‌ها','incidents'=>'حوادث','actions'=>'CAPA','inspections'=>'بازرسی‌ها'] as $k=>$v)<a href="{{ route('reports.export',['type'=>$k]) }}" class="rounded-xl bg-emerald-50 px-4 py-2 text-xs font-bold text-emerald-700">{{ $v }}</a>@endforeach</div>
<form class="mb-5 flex flex-wrap items-end gap-3 rounded-2xl border border-slate-200 bg-white p-4"><div><span class="mb-1 block text-xs font-bold">از تاریخ</span><div class="relative"><input type="text" name="from" value="{{ $fromVal }}" data-jdatepicker="date" autocomplete="off" dir="ltr" class="rounded-xl border border-slate-200 py-2 pl-3 pr-9"><span class="pointer-events-none absolute inset-y-0 right-0 flex items-center pr-2.5 text-slate-400"><svg xmlns="http://www.w3.org/2000/svg" class="h-4 w-4" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="1.8"><rect x="3" y="4" width="18" height="18" rx="2" ry="2"/><line x1="16" y1="2" x2="16" y2="6"/><line x1="8" y1="2" x2="8" y2="6"/><line x1="3" y1="10" x2="21" y2="10"/></svg></span></div></div><div><span class="mb-1 block text-xs font-bold">تا تاریخ</span><div class="relative"><input type="text" name="to" value="{{ $toVal }}" data-jdatepicker="date" autocomplete="off" dir="ltr" class="rounded-xl border border-slate-200 py-2 pl-3 pr-9"><span class="pointer-events-none absolute inset-y-0 right-0 flex items-center pr-2.5 text-slate-400"><svg xmlns="http://www.w3.org/2000/svg" class="h-4 w-4" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="1.8"><rect x="3" y="4" width="18" height="18" rx="2" ry="2"/><line x1="16" y1="2" x2="16" y2="6"/><line x1="8" y1="2" x2="8" y2="6"/><line x1="3" y1="10" x2="21" y2="10"/></svg></span></div></div><button class="rounded-xl bg-slate-900 px-5 py-2.5 text-sm font-bold text-white">به‌روزرسانی گزارش</button><button type="button" onclick="print()" class="rounded-xl border border-slate-200 px-5 py-2.5 text-sm font-bold">چاپ / PDF</button></form>
<div class="grid gap-5 lg:grid-cols-2"><section class="rounded-2xl border border-slate-200 bg-white p-6"><div class="flex items-center justify-between"><h3 class="font-black">توزیع سطح ریسک‌ها</h3><span class="text-xs text-slate-400">{{ $riskByLevel->sum() }} مورد</span></div><div class="mx-auto mt-5 h-64 max-w-sm"><canvas data-chart='@json($riskChart)'></canvas></div></section><section class="rounded-2xl border border-slate-200 bg-white p-6"><h3 class="font-black">ترکیب رویدادها</h3><div class="mt-5 h-64"><canvas data-chart='@json($incidentChart)'></canvas></div></section></div>
<div class="mt-5 w-full lg:w-1/2"><section class="w-full rounded-2xl border border-slate-200 bg-white p-6"><div class="mb-4 flex items-center justify-between"><div><h3 class="font-black">مقایسه عملکرد واحدها</h3><p class="text-xs text-slate-400">ریسک ثبت‌شده، اقدام باز و میانگین امتیاز بازرسی</p></div><span class="text-xs text-slate-400">در بازه انتخاب‌شده</span></div><div class="h-64 w-full"><canvas class="!h-full !w-full" data-chart='@json($departmentChart)'></canvas></div></section></div>
<section class="mt-5 overflow-hidden rounded-2xl border border-slate-200 bg-white"><div class="border-b p-5"><h3 class="font-black">عملکرد واحدهای سازمانی</h3><p class="text-xs text-slate-400">مقایسه ریسک، اقدام باز و میانگین امتیاز بازرسی</p></div><div class="overflow-x-auto"><table class="w-full min-w-[700px] text-right text-sm"><thead class="bg-slate-50 text-xs text-slate-500"><tr><th class="p-4">واحد</th><th>کاربران</th><th>ریسک‌های ثبت‌شده</th><th>اقدامات باز</th><th>میانگین بازرسی</th><th>ارزیابی</th></tr></thead><tbody class="divide-y">@foreach($departmentStats as $d)<tr><td class="p-4 font-bold">{{ $d->name }}</td><td>{{ $d->users_count }}</td><td>{{ $d->risks_count }}</td><td class="{{ $d->actions_open>3?'font-bold text-rose-600':'' }}">{{ $d->actions_open }}</td><td>{{ $d->inspection_avg }}٪</td><td><span class="rounded-full px-2 py-1 text-xs font-bold {{ $d->inspection_avg>=85?'bg-emerald-100 text-emerald-700':($d->inspection_avg>=70?'bg-amber-100 text-amber-700':'bg-rose-100 text-rose-700') }}">{{ $d->inspection_avg>=85?'مطلوب':($d->inspection_avg>=70?'نیازمند بهبود':'نامطلوب') }}</span></td></tr>@endforeach</tbody></table></div></section>@endsection
