<?php
use Illuminate\Database\Migrations\Migration; use Illuminate\Database\Schema\Blueprint; use Illuminate\Support\Facades\Schema;
return new class extends Migration {
 public function up():void {
  Schema::create('departments',function(Blueprint $t){$t->id();$t->string('name');$t->string('code')->unique();$t->string('location')->nullable();$t->boolean('is_active')->default(true);$t->timestamps();});
  Schema::create('users',function(Blueprint $t){$t->id();$t->string('name');$t->string('personnel_code')->nullable()->unique();$t->string('phone')->nullable()->unique();$t->string('email')->unique();$t->timestamp('email_verified_at')->nullable();$t->string('password');$t->string('role')->index();$t->foreignId('department_id')->nullable()->constrained()->nullOnDelete();$t->boolean('is_active')->default(true);$t->timestamp('last_login_at')->nullable();$t->rememberToken();$t->timestamps();});
  Schema::table('departments',fn(Blueprint $t)=>$t->foreignId('manager_id')->nullable()->constrained('users')->nullOnDelete());
  Schema::create('password_reset_tokens',function(Blueprint $t){$t->string('email')->primary();$t->string('token');$t->timestamp('created_at')->nullable();});
  Schema::create('sessions',function(Blueprint $t){$t->string('id')->primary();$t->foreignId('user_id')->nullable()->index();$t->string('ip_address',45)->nullable();$t->text('user_agent')->nullable();$t->longText('payload');$t->integer('last_activity')->index();});
  Schema::create('cache',function(Blueprint $t){$t->string('key')->primary();$t->mediumText('value');$t->integer('expiration');}); Schema::create('cache_locks',function(Blueprint $t){$t->string('key')->primary();$t->string('owner');$t->integer('expiration');});
  Schema::create('jobs',function(Blueprint $t){$t->id();$t->string('queue')->index();$t->longText('payload');$t->unsignedTinyInteger('attempts');$t->unsignedInteger('reserved_at')->nullable();$t->unsignedInteger('available_at');$t->unsignedInteger('created_at');});
  Schema::create('job_batches',function(Blueprint $t){$t->string('id')->primary();$t->string('name');$t->integer('total_jobs');$t->integer('pending_jobs');$t->integer('failed_jobs');$t->longText('failed_job_ids');$t->mediumText('options')->nullable();$t->integer('cancelled_at')->nullable();$t->integer('created_at');$t->integer('finished_at')->nullable();});
  Schema::create('failed_jobs',function(Blueprint $t){$t->id();$t->string('uuid')->unique();$t->text('connection');$t->text('queue');$t->longText('payload');$t->longText('exception');$t->timestamp('failed_at')->useCurrent();});
  Schema::create('checklists',function(Blueprint $t){$t->id();$t->string('title');$t->string('category');$t->text('description')->nullable();$t->string('version')->default('1.0');$t->boolean('is_active')->default(true);$t->foreignId('created_by')->constrained('users');$t->timestamps();});
  Schema::create('checklist_items',function(Blueprint $t){$t->id();$t->foreignId('checklist_id')->constrained()->cascadeOnDelete();$t->text('question');$t->text('guidance')->nullable();$t->unsignedTinyInteger('weight')->default(1);$t->boolean('is_critical')->default(false);$t->unsignedInteger('sort_order')->default(0);$t->timestamps();});
  Schema::create('inspections',function(Blueprint $t){$t->id();$t->string('code')->unique();$t->string('title');$t->foreignId('checklist_id')->constrained();$t->foreignId('department_id')->constrained();$t->foreignId('inspector_id')->constrained('users');$t->timestamp('scheduled_at');$t->timestamp('started_at')->nullable();$t->timestamp('completed_at')->nullable();$t->string('status')->default('planned')->index();$t->string('location')->nullable();$t->text('summary')->nullable();$t->decimal('score',5,2)->nullable();$t->timestamps();});
  Schema::create('inspection_responses',function(Blueprint $t){$t->id();$t->foreignId('inspection_id')->constrained()->cascadeOnDelete();$t->foreignId('checklist_item_id')->constrained()->cascadeOnDelete();$t->string('answer');$t->text('note')->nullable();$t->string('evidence_path')->nullable();$t->timestamps();$t->unique(['inspection_id','checklist_item_id']);});
  Schema::create('risks',function(Blueprint $t){$t->id();$t->string('code')->unique();$t->string('title');$t->text('description');$t->string('category');$t->foreignId('department_id')->constrained();$t->foreignId('inspection_id')->nullable()->constrained()->nullOnDelete();$t->foreignId('identified_by')->constrained('users');$t->unsignedTinyInteger('likelihood');$t->unsignedTinyInteger('severity');$t->unsignedTinyInteger('risk_score');$t->string('risk_level')->index();$t->text('existing_controls')->nullable();$t->text('proposed_controls')->nullable();$t->string('status')->default('open')->index();$t->timestamps();});
  Schema::create('incidents',function(Blueprint $t){$t->id();$t->string('code')->unique();$t->string('type')->index();$t->string('title');$t->text('description');$t->foreignId('department_id')->constrained();$t->foreignId('reported_by')->constrained('users');$t->timestamp('occurred_at');$t->string('location');$t->string('injury_level')->nullable();$t->unsignedInteger('lost_days')->default(0);$t->text('immediate_actions')->nullable();$t->text('root_cause')->nullable();$t->string('status')->default('reported')->index();$t->timestamps();});
  Schema::create('corrective_actions',function(Blueprint $t){$t->id();$t->string('code')->unique();$t->string('title');$t->text('description');$t->nullableMorphs('actionable');$t->foreignId('department_id')->constrained();$t->foreignId('assignee_id')->constrained('users');$t->foreignId('assigned_by')->constrained('users');$t->string('priority')->default('medium')->index();$t->date('due_date')->index();$t->string('status')->default('assigned')->index();$t->text('result')->nullable();$t->timestamp('completed_at')->nullable();$t->foreignId('verified_by')->nullable()->constrained('users')->nullOnDelete();$t->timestamp('verified_at')->nullable();$t->text('rejection_reason')->nullable();$t->timestamps();});
  Schema::create('attachments',function(Blueprint $t){$t->id();$t->morphs('attachable');$t->foreignId('uploaded_by')->constrained('users');$t->string('original_name');$t->string('path');$t->string('mime_type')->nullable();$t->unsignedBigInteger('size')->default(0);$t->timestamps();});
  Schema::create('activity_logs',function(Blueprint $t){$t->id();$t->foreignId('user_id')->nullable()->constrained('users')->nullOnDelete();$t->string('event');$t->nullableMorphs('subject');$t->text('description');$t->string('ip_address',45)->nullable();$t->timestamp('created_at')->useCurrent();});
  Schema::create('settings',function(Blueprint $t){$t->string('key')->primary();$t->text('value')->nullable();});
 }
 public function down():void { Schema::table('departments',fn(Blueprint $t)=>$t->dropConstrainedForeignId('manager_id')); foreach(['settings','activity_logs','attachments','corrective_actions','incidents','risks','inspection_responses','inspections','checklist_items','checklists','failed_jobs','job_batches','jobs','cache_locks','cache','sessions','password_reset_tokens','users','departments'] as $table) Schema::dropIfExists($table); }
};
