@extends('layouts.app') @php $editing=$examination->exists; @endphp @section('title',$editing?'ویرایش معاینه':'ثبت معاینه طب کار') @section('page-title',$editing?'ویرایش معاینه طب کار':'ثبت معاینه طب کار') @section('content')
<form method="post" enctype="multipart/form-data" action="{{ $editing?route('health.examinations.update',$examination):route('health.examinations.store') }}" class="mx-auto max-w-5xl">@csrf @if($editing)@method('PUT')@endif<div class="overflow-hidden rounded-3xl border border-slate-200 bg-white shadow-sm"><div class="border-b border-slate-200 bg-gradient-to-l from-cyan-50 via-sky-50 to-white p-6"><h2 class="text-lg font-black">اطلاعات معاینه</h2><p class="mt-1 text-xs text-slate-500">نتیجه طب کار، صلاحیت شغلی و سررسید بعدی را ثبت کنید.</p></div><div class="grid gap-5 p-6 md:grid-cols-2">
<label><span class="mb-2 block text-sm font-bold">پرونده کارمند *</span><select name="occupational_health_profile_id" class="w-full rounded-xl border border-slate-200 px-4 py-3">@foreach($profiles as $p)<option value="{{ $p->id }}" @selected(old('occupational_health_profile_id',$selectedProfile?:$examination->occupational_health_profile_id)==$p->id)>{{ $p->user->name }} — {{ $p->job_title }} — {{ $p->user->department?->name }}</option>@endforeach</select></label>
<label><span class="mb-2 block text-sm font-bold">نوع معاینه *</span><select name="examination_type" class="w-full rounded-xl border border-slate-200 px-4 py-3">@foreach(['pre_employment'=>'بدو استخدام','periodic'=>'دوره‌ای','return_to_work'=>'بازگشت به کار','job_change'=>'تغییر شغل','special'=>'موردی','exit'=>'پایان خدمت'] as $k=>$v)<option value="{{ $k }}" @selected(old('examination_type',$examination->examination_type?:'periodic')===$k)>{{ $v }}</option>@endforeach</select></label>
<label><span class="mb-2 block text-sm font-bold">تاریخ معاینه *</span><input name="examination_date" value="{{ old('examination_date',$examination->examination_date?jdate($examination->examination_date)->format('Y/m/d'):'') }}" class="w-full rounded-xl border border-slate-200 px-4 py-3" required></label><label><span class="mb-2 block text-sm font-bold">تاریخ معاینه بعدی</span><input name="next_examination_date" value="{{ old('next_examination_date',$examination->next_examination_date?jdate($examination->next_examination_date)->format('Y/m/d'):'') }}" class="w-full rounded-xl border border-slate-200 px-4 py-3"></label>
<label><span class="mb-2 block text-sm font-bold">مرکز طب کار</span><input name="health_center" value="{{ old('health_center',$examination->health_center) }}" class="w-full rounded-xl border border-slate-200 px-4 py-3"></label><label><span class="mb-2 block text-sm font-bold">پزشک</span><input name="physician" value="{{ old('physician',$examination->physician) }}" class="w-full rounded-xl border border-slate-200 px-4 py-3"></label>
<label><span class="mb-2 block text-sm font-bold">صلاحیت پزشکی *</span><select name="fitness_status" class="w-full rounded-xl border border-slate-200 px-4 py-3">@foreach(['fit'=>'مجاز به کار','fit_with_restrictions'=>'مجاز با محدودیت','temporarily_unfit'=>'عدم صلاحیت موقت','unfit'=>'عدم صلاحیت','pending'=>'در انتظار ارزیابی'] as $k=>$v)<option value="{{ $k }}" @selected(old('fitness_status',$examination->fitness_status?:'fit')===$k)>{{ $v }}</option>@endforeach</select></label><label><span class="mb-2 block text-sm font-bold">منبع داده *</span><select name="data_source" class="w-full rounded-xl border border-slate-200 px-4 py-3">@foreach(['manual'=>'ثبت داخلی','healthyline'=>'Healthyline','import'=>'Import','other'=>'سایر'] as $k=>$v)<option value="{{ $k }}" @selected(old('data_source',$examination->data_source?:'manual')===$k)>{{ $v }}</option>@endforeach</select></label>
<label class="md:col-span-2"><span class="mb-2 block text-sm font-bold">نتیجه / نظر طب کار</span><textarea name="result" rows="3" class="w-full rounded-xl border border-slate-200 px-4 py-3">{{ old('result',$examination->result) }}</textarea></label><label class="md:col-span-2"><span class="mb-2 block text-sm font-bold">محدودیت‌های شغلی</span><textarea name="restrictions" rows="3" class="w-full rounded-xl border border-slate-200 px-4 py-3">{{ old('restrictions',$examination->restrictions) }}</textarea></label>
<div class="rounded-2xl border border-amber-200 bg-amber-50 p-4 md:col-span-2"><label class="flex items-center gap-2 font-bold text-amber-900"><input type="checkbox" name="follow_up_required" value="1" @checked(old('follow_up_required',$examination->follow_up_required))> نیازمند پیگیری پزشکی</label><input name="follow_up_date" value="{{ old('follow_up_date',$examination->follow_up_date?jdate($examination->follow_up_date)->format('Y/m/d'):'') }}" placeholder="تاریخ پیگیری" class="mt-3 w-full rounded-xl border border-amber-200 bg-white px-4 py-3 md:w-72"></div>
<label><span class="mb-2 block text-sm font-bold">پیوست</span><input type="file" name="attachment" class="w-full rounded-xl border border-slate-200 px-3 py-2.5 text-sm" accept=".jpg,.jpeg,.png,.pdf,.doc,.docx">@if($editing&&$examination->attachment_name)<div class="mt-1 text-xs text-slate-400">فایل فعلی: {{ $examination->attachment_name }}</div>@endif</label><label><span class="mb-2 block text-sm font-bold">External ID</span><input name="external_id" value="{{ old('external_id',$examination->external_id) }}" placeholder="برای Integration آینده" class="w-full rounded-xl border border-slate-200 px-4 py-3"></label>
<label class="md:col-span-2"><span class="mb-2 block text-sm font-bold">یادداشت</span><textarea name="notes" rows="3" class="w-full rounded-xl border border-slate-200 px-4 py-3">{{ old('notes',$examination->notes) }}</textarea></label></div></div><div class="mt-5 flex justify-end gap-2"><a href="{{ $editing?route('health.profiles.show',$examination->profile):route('health.examinations.index') }}" class="rounded-xl border border-slate-200 bg-white px-5 py-2.5 text-sm font-bold">انصراف</a><button class="rounded-xl bg-sky-600 px-6 py-2.5 text-sm font-bold text-white shadow-lg shadow-sky-200">{{ $editing?'ذخیره تغییرات':'ثبت معاینه' }}</button></div></form>
@endsection
