@extends('layouts.app')
@section('title','چک‌لیست‌ها')
@section('page-title','بانک چک‌لیست‌های بازرسی')
@section('content')
<div class="mb-5 flex items-center justify-between"><div><h2 class="text-xl font-black">الگوهای استاندارد بازرسی</h2><p class="mt-1 text-sm text-slate-500">نسخه‌بندی و مدیریت سؤالات بازرسی</p></div><a href="{{ route('checklists.create') }}" class="rounded-xl bg-emerald-600 px-4 py-3 text-sm font-bold text-white hover:bg-emerald-700">+ چک‌لیست جدید</a></div>
<form method="get" action="{{ route('checklists.index') }}" class="mb-5 rounded-2xl border border-emerald-200 bg-emerald-50 p-4 shadow-sm"><label for="checklist-search" class="mb-2 block text-sm font-black text-emerald-950">جستجوی چک‌لیست</label><div class="flex flex-col gap-3 sm:flex-row"><div class="flex flex-1 flex-row-reverse items-center overflow-hidden rounded-xl border-2 border-emerald-400 bg-white shadow-sm focus-within:border-emerald-600 focus-within:ring-2 focus-within:ring-emerald-200"><span class="flex shrink-0 items-center border-l border-emerald-200 px-3 text-slate-500">@include('components.icon',['name'=>'search'])</span><input id="checklist-search" name="search" value="{{ $search }}" type="search" dir="rtl" placeholder="نام، دسته‌بندی یا توضیحات چک‌لیست" class="min-w-0 flex-1 border-0 bg-transparent px-4 py-3 text-sm text-slate-800 outline-none placeholder:text-slate-500 focus:ring-0"></div><button type="submit" class="rounded-xl bg-emerald-700 px-5 py-3 text-sm font-bold text-white shadow-sm hover:bg-emerald-800">جستجو</button>@if($search !== '')<a href="{{ route('checklists.index') }}" class="rounded-xl border border-emerald-300 bg-white px-5 py-3 text-center text-sm font-bold text-emerald-800 hover:bg-emerald-50">پاک کردن</a>@endif</div></form>
<div class="grid gap-4 md:grid-cols-2 xl:grid-cols-3">@forelse($checklists as $c)<div class="rounded-2xl border border-slate-200 bg-white p-5"><div class="flex justify-between"><span class="rounded-lg bg-slate-100 px-2 py-1 text-[11px] font-bold">{{ $c->category }}</span><span class="rounded-lg px-2 py-1 text-[11px] font-bold {{ $c->is_active?'bg-emerald-50 text-emerald-700':'bg-slate-100 text-slate-500' }}">{{ $c->is_active?'فعال':'غیرفعال' }}</span></div><h3 class="mt-4 font-black">{{ $c->title }}</h3><div class="mt-5 flex items-center justify-between border-t pt-4 text-xs"><span>{{ $c->items_count }} سؤال فعال · نسخه {{ $c->version }}</span><div class="flex items-center gap-3"><a href="{{ route('checklists.show',$c) }}" class="text-emerald-700" title="مشاهده چک‌لیست" aria-label="مشاهده چک‌لیست">@include('components.icon',['name'=>'eye'])<span class="sr-only">مشاهده</span></a><a href="{{ route('checklists.edit',$c) }}" class="text-blue-400 hover:text-blue-500" title="ویرایش چک‌لیست" aria-label="ویرایش چک‌لیست">@include('components.icon',['name'=>'edit'])<span class="sr-only">ویرایش</span></a><form method="post" action="{{ route('checklists.toggle',$c) }}">@csrf @method('PATCH')<button type="submit" class="text-black" title="{{ $c->is_active?'غیرفعال کردن چک‌لیست':'فعال کردن چک‌لیست' }}" aria-label="{{ $c->is_active?'غیرفعال کردن چک‌لیست':'فعال کردن چک‌لیست' }}">@include('components.icon',['name'=>$c->is_active?'pause':'play'])<span class="sr-only">{{ $c->is_active?'غیرفعال کردن':'فعال کردن' }}</span></button></form><form method="post" action="{{ route('checklists.destroy',$c) }}" onsubmit="return confirm('این چک‌لیست حذف شود؟')">@csrf @method('DELETE')<button type="submit" class="text-rose-600" title="حذف چک‌لیست" aria-label="حذف چک‌لیست">@include('components.icon',['name'=>'trash'])<span class="sr-only">حذف</span></button></form></div></div></div>@empty<div class="rounded-2xl border border-dashed border-slate-300 bg-white p-10 text-center text-sm font-bold text-slate-500 md:col-span-2 xl:col-span-3">چک‌لیستی با این مشخصات یافت نشد.</div>@endforelse</div>
<div class="mt-5">{{ $checklists->links() }}</div>
@endsection
