<?php
namespace App\Http\Controllers;
use App\Models\{CorrectiveAction,Department,User,Attachment}; use Illuminate\Http\Request;
class CorrectiveActionController extends Controller {
 public function index(Request $r){$q=CorrectiveAction::with('department','assignee')->latest();if($r->user()->hasRole('unit_manager'))$q->where('department_id',$r->user()->department_id);if($r->user()->hasRole('inspector'))$q->where('assignee_id',$r->user()->id);if($r->filled('status'))$q->where('status',$r->status);return view('actions.index',['actions'=>$q->paginate(15)]);}
 public function create(Request $r){$sourceType=$r->filled('risk')?'risk':($r->filled('incident')?'incident':null);$sourceId=$sourceType?$r->integer($sourceType):null;return view('actions.create',['departments'=>Department::where('is_active',true)->get(),'users'=>User::where('is_active',true)->get(),'sourceType'=>$sourceType,'sourceId'=>$sourceId]);}
 public function store(Request $r){if($r->filled('due_date'))$r->merge(['due_date'=>optional(jalaliToCarbon($r->input('due_date')))?->toDateString()??$r->input('due_date')]);$d=$r->validate(['title'=>'required|max:190','description'=>'required','department_id'=>'required|exists:departments,id','assignee_id'=>'required|exists:users,id','priority'=>'required|in:low,medium,high,critical','due_date'=>'required|date|after_or_equal:today','source_type'=>'nullable|in:risk,incident','source_id'=>'nullable|integer']);if(!empty($d['source_type'])&&!empty($d['source_id'])){$model=$d['source_type']==='risk'?\App\Models\Risk::class:\App\Models\Incident::class;abort_unless($model::whereKey($d['source_id'])->exists(),422,'منبع اقدام معتبر نیست.');$d['actionable_type']=$model;$d['actionable_id']=$d['source_id'];}unset($d['source_type'],$d['source_id']);$d+=['code'=>$this->code('ACT'),'assigned_by'=>$r->user()->id,'status'=>'assigned'];$a=CorrectiveAction::create($d);$this->log('assigned',$a,'اقدام اصلاحی ارجاع شد.');return redirect()->route('actions.show',$a)->with('success','اقدام اصلاحی ارجاع شد.');}
 public function show(CorrectiveAction $action){$u=auth()->user();abort_if($u->hasRole('unit_manager')&&$action->department_id!==$u->department_id,403);abort_if($u->hasRole('inspector')&&$action->assignee_id!==$u->id,403);$action->load('department','assignee','attachments');return view('actions.show',compact('action'));}
 public function submit(Request $r,CorrectiveAction $action){abort_unless($action->assignee_id===$r->user()->id||$r->user()->hasRole(['admin','hse_manager']),403);$d=$r->validate(['result'=>'required|min:10','evidence'=>'nullable|file|max:10240|mimes:jpg,jpeg,png,pdf,doc,docx']);$action->update(['result'=>$d['result'],'status'=>'pending_verification','completed_at'=>now()]);if($r->hasFile('evidence')){$f=$r->file('evidence');Attachment::create(['attachable_type'=>$action::class,'attachable_id'=>$action->id,'uploaded_by'=>$r->user()->id,'original_name'=>$f->getClientOriginalName(),'path'=>$f->store('actions','public'),'mime_type'=>$f->getMimeType(),'size'=>$f->getSize()]);}$this->log('submitted',$action,'اقدام برای تأیید نهایی ارسال شد.');return back()->with('success','نتیجه اقدام برای بررسی HSE ارسال شد.');}
 public function verify(Request $r,CorrectiveAction $action){$d=$r->validate(['decision'=>'required|in:verify,reject','rejection_reason'=>'required_if:decision,reject|nullable']);$action->update($d['decision']==='verify'?['status'=>'verified','verified_by'=>$r->user()->id,'verified_at'=>now(),'rejection_reason'=>null]:['status'=>'rejected','rejection_reason'=>$d['rejection_reason']]);$this->log($d['decision'],$action,$d['decision']==='verify'?'اقدام اصلاحی تأیید شد.':'اقدام برای اصلاح مجدد برگشت داده شد.');return back()->with('success','وضعیت اقدام به‌روزرسانی شد.');}
}
