<?php
namespace App\Http\Controllers;
use App\Models\{OccupationalHealthProfile,User};
use Illuminate\Http\Request;
class HealthProfileController extends Controller {
 private function scope($q,Request $r){return $q->when($r->user()->hasRole('unit_manager'),fn($x)=>$x->whereHas('user',fn($u)=>$u->where('department_id',$r->user()->department_id)));}
 private function authorizeView(OccupationalHealthProfile $profile,Request $r):void{if($r->user()->hasRole('unit_manager'))abort_unless($profile->user?->department_id===$r->user()->department_id,403);}
 public function index(Request $r){$q=$this->scope(OccupationalHealthProfile::with('user.department'),$r);if($r->filled('q'))$q->whereHas('user',fn($u)=>$u->where('name','like','%'.$r->q.'%')->orWhere('personnel_code','like','%'.$r->q.'%'));if($r->filled('fitness_status'))$q->where('fitness_status',$r->fitness_status);return view('health.profiles.index',['profiles'=>$q->latest()->paginate(15)->withQueryString()]);}
 public function create(Request $r){abort_unless($r->user()->hasRole(['admin','hse_manager']),403);return view('health.profiles.form',['profile'=>new OccupationalHealthProfile(),'users'=>User::where('is_active',true)->whereDoesntHave('occupationalHealthProfile')->with('department')->orderBy('name')->get()]);}
 public function store(Request $r){$r->merge(['follow_up_required'=>$r->boolean('follow_up_required')]);abort_unless($r->user()->hasRole(['admin','hse_manager']),403);$this->dates($r,['employment_start_date','follow_up_date']);$d=$this->validated($r,true);$d+=['created_by'=>$r->user()->id,'updated_by'=>$r->user()->id];$p=OccupationalHealthProfile::create($d);$this->log('created',$p,'پرونده سلامت شغلی ایجاد شد.');return redirect()->route('health.profiles.show',$p)->with('success','پرونده سلامت ایجاد شد.');}
 public function show(Request $r,OccupationalHealthProfile $profile){$this->authorizeView($profile,$r);$profile->load('user.department','examinations.creator');return view('health.profiles.show',compact('profile'));}
 public function edit(Request $r,OccupationalHealthProfile $profile){abort_unless($r->user()->hasRole(['admin','hse_manager']),403);$profile->load('user.department');return view('health.profiles.form',compact('profile'),['users'=>collect([$profile->user])]);}
 public function update(Request $r,OccupationalHealthProfile $profile){$r->merge(['follow_up_required'=>$r->boolean('follow_up_required')]);abort_unless($r->user()->hasRole(['admin','hse_manager']),403);$this->dates($r,['employment_start_date','follow_up_date']);$d=$this->validated($r,false);unset($d['user_id']);$d['updated_by']=$r->user()->id;$profile->update($d);$this->log('updated',$profile,'پرونده سلامت شغلی به‌روزرسانی شد.');return redirect()->route('health.profiles.show',$profile)->with('success','پرونده سلامت به‌روزرسانی شد.');}
 private function validated(Request $r,bool $creating):array{return $r->validate(['user_id'=>[$creating?'required':'nullable','exists:users,id',$creating?'unique:occupational_health_profiles,user_id':'nullable'],'job_title'=>'required|max:190','employment_start_date'=>'nullable|date','fitness_status'=>'required|in:fit,fit_with_restrictions,temporarily_unfit,unfit,pending','medical_restrictions'=>'nullable|max:3000','follow_up_required'=>'nullable|boolean','follow_up_date'=>'nullable|date','occupational_disease_status'=>'nullable|in:none,suspected,confirmed,under_review','notes'=>'nullable|max:5000']);}
 private function dates(Request $r,array $fields):void{foreach($fields as $f)if($r->filled($f))$r->merge([$f=>optional(jalaliToCarbon($r->input($f)))->toDateString()??$r->input($f)]);}
}
