<?php
namespace App\Http\Controllers;
use App\Models\{Attachment,Department,Incident}; use Illuminate\Http\Request;
class IncidentController extends Controller {
 public function index(Request $r){$q=Incident::with('department','reporter')->latest('occurred_at');if($r->user()->hasRole('unit_manager'))$q->where('department_id',$r->user()->department_id);if($r->user()->hasRole('inspector'))$q->where('reported_by',$r->user()->id);if($r->filled('type'))$q->where('type',$r->type);if($r->filled('q'))$q->where(fn($x)=>$x->where('title','like','%'.$r->q.'%')->orWhere('code','like','%'.$r->q.'%'));return view('incidents.index',['incidents'=>$q->paginate(15)->withQueryString()]);}
 public function create(){return view('incidents.create',['departments'=>Department::where('is_active',true)->get()]);}
 public function store(Request $r){if($r->filled('occurred_at'))$r->merge(['occurred_at'=>optional(jalaliToCarbon($r->input('occurred_at')))?->toDateTimeString()??$r->input('occurred_at')]);$d=$r->validate(['type'=>'required|in:incident,near_miss,occupational_disease,environmental','title'=>'required|max:190','description'=>'required','department_id'=>'required|exists:departments,id','occurred_at'=>'required|date|before_or_equal:now','location'=>'required|max:190','activity'=>'nullable|max:500','involved_people_text'=>'nullable|max:2000','consequences'=>'nullable|max:3000','injury_level'=>'nullable|max:100','lost_days'=>'nullable|integer|min:0','immediate_actions'=>'nullable','documents.*'=>'nullable|file|max:10240|mimes:jpg,jpeg,png,pdf,doc,docx']);if($r->user()->hasRole('unit_manager'))$d['department_id']=$r->user()->department_id;$d['involved_people']=array_values(array_filter(array_map('trim',preg_split('/[\r\n,]+/',$d['involved_people_text']??''))));unset($d['involved_people_text'],$d['documents']);$d+=['code'=>$this->code('INC'),'reported_by'=>$r->user()->id,'status'=>'reported'];$incident=Incident::create($d);foreach($r->file('documents',[]) as $f)Attachment::create(['attachable_type'=>$incident::class,'attachable_id'=>$incident->id,'uploaded_by'=>$r->user()->id,'original_name'=>$f->getClientOriginalName(),'path'=>$f->store('incidents','public'),'mime_type'=>$f->getMimeType(),'size'=>$f->getSize()]);$this->log('created',$incident,'رویداد HSE و مستندات آن ثبت شد.');return redirect()->route('incidents.show',$incident)->with('success','گزارش اولیه ثبت شد.');}
 public function show(Incident $incident){$u=auth()->user();abort_if($u->hasRole('unit_manager')&&$incident->department_id!==$u->department_id,403);abort_if($u->hasRole('inspector')&&$incident->reported_by!==$u->id,403);$incident->load('department','reporter','actions.assignee','attachments');return view('incidents.show',compact('incident'));}
 public function investigate(Request $r,Incident $incident){$d=$r->validate(['root_cause'=>'required|min:10','rca_method'=>'required|in:five_whys,fishbone,fault_tree,combined','five_whys'=>'nullable|array|max:5','five_whys.*'=>'nullable|max:1000','fishbone'=>'nullable|array','fishbone.*'=>'nullable|max:2000','fault_tree_text'=>'nullable|max:5000','status'=>'required|in:investigating,actions_pending,closed']);$d['five_whys']=array_values(array_filter($d['five_whys']??[]));$d['fishbone']=array_filter($d['fishbone']??[]);$d['fault_tree']=array_values(array_filter(array_map('trim',preg_split('/[\r\n]+/',$d['fault_tree_text']??''))));unset($d['fault_tree_text']);$incident->update($d);$this->log('investigated',$incident,'RCA ساختاریافته برای حادثه ثبت شد.');return back()->with('success','تحلیل علت ریشه‌ای به‌روزرسانی شد.');}
}
