<?php
namespace App\Http\Controllers;
use App\Models\{Department,Incident}; use Illuminate\Http\Request;
class IncidentController extends Controller {
 public function index(Request $r){$q=Incident::with('department','reporter')->latest('occurred_at');if($r->user()->hasRole('unit_manager'))$q->where('department_id',$r->user()->department_id);if($r->user()->hasRole('inspector'))$q->where('reported_by',$r->user()->id);return view('incidents.index',['incidents'=>$q->paginate(15)]);}
 public function create(){return view('incidents.create',['departments'=>Department::where('is_active',true)->get()]);}
 public function store(Request $r){if($r->filled('occurred_at'))$r->merge(['occurred_at'=>optional(jalaliToCarbon($r->input('occurred_at')))?->toDateTimeString()??$r->input('occurred_at')]);$d=$r->validate(['type'=>'required|in:incident,near_miss,occupational_disease,environmental','title'=>'required|max:190','description'=>'required','department_id'=>'required|exists:departments,id','occurred_at'=>'required|date|before_or_equal:now','location'=>'required|max:190','injury_level'=>'nullable|max:100','lost_days'=>'nullable|integer|min:0','immediate_actions'=>'nullable']);if($r->user()->hasRole('unit_manager'))$d['department_id']=$r->user()->department_id;$d+=['code'=>$this->code('INC'),'reported_by'=>$r->user()->id,'status'=>'reported'];$incident=Incident::create($d);$this->log('created',$incident,'رویداد HSE ثبت شد.');return redirect()->route('incidents.show',$incident)->with('success','گزارش اولیه ثبت شد.');}
 public function show(Incident $incident){$u=auth()->user();abort_if($u->hasRole('unit_manager')&&$incident->department_id!==$u->department_id,403);abort_if($u->hasRole('inspector')&&$incident->reported_by!==$u->id,403);$incident->load('department','reporter','actions.assignee','attachments');return view('incidents.show',compact('incident'));}
 public function investigate(Request $r,Incident $incident){$d=$r->validate(['root_cause'=>'required|min:10','status'=>'required|in:investigating,actions_pending,closed']);$incident->update($d);$this->log('investigated',$incident,'نتیجه بررسی و علت ریشه‌ای ثبت شد.');return back()->with('success','بررسی حادثه به‌روزرسانی شد.');}
}
