<?php
namespace App\Http\Controllers;
use App\Models\{Checklist,Department,Inspection,InspectionResponse}; use Illuminate\Http\Request; use Illuminate\Support\Facades\DB;
class InspectionController extends Controller {
 public function index(Request $r){$q=Inspection::with('department','inspector','checklist')->latest('scheduled_at');if($r->user()->hasRole('inspector'))$q->where('inspector_id',$r->user()->id);if($r->user()->hasRole('unit_manager'))$q->where('department_id',$r->user()->department_id);return view('inspections.index',['inspections'=>$q->paginate(15)]);}
 public function create(){return view('inspections.create',['checklists'=>Checklist::where('is_active',true)->get(),'departments'=>Department::where('is_active',true)->get(),'inspectors'=>\App\Models\User::where('role','inspector')->where('is_active',true)->get()]);}
 public function store(Request $r){if($r->filled('scheduled_at'))$r->merge(['scheduled_at'=>optional(jalaliToCarbon($r->input('scheduled_at')))?->toDateTimeString()??$r->input('scheduled_at')]);$d=$r->validate(['title'=>'required|max:190','checklist_id'=>'required|exists:checklists,id','department_id'=>'required|exists:departments,id','inspector_id'=>'required|exists:users,id','scheduled_at'=>'required|date','location'=>'nullable|max:190']);if($r->user()->hasRole('inspector'))$d['inspector_id']=$r->user()->id;$d['code']=$this->code('INS');$i=Inspection::create($d);$this->log('created',$i,'بازرسی جدید برنامه‌ریزی شد.');return redirect()->route('inspections.show',$i)->with('success','بازرسی با موفقیت برنامه‌ریزی شد.');}
 public function show(Inspection $inspection){$u=auth()->user();abort_if($u->hasRole('unit_manager')&&$inspection->department_id!==$u->department_id,403);abort_if($u->hasRole('inspector')&&$inspection->inspector_id!==$u->id,403);$inspection->load('department','inspector','checklist.items','responses.item');return view('inspections.show',compact('inspection'));}
 public function complete(Request $r,Inspection $inspection){abort_unless($r->user()->hasRole(['admin','hse_manager'])||$inspection->inspector_id===$r->user()->id,403);$items=$inspection->checklist->items;$data=$r->validate(['responses'=>'required|array','responses.*.answer'=>'required|in:compliant,noncompliant,na','responses.*.note'=>'nullable|max:2000']);DB::transaction(function()use($inspection,$items,$data){foreach($items as $item){$answer=$data['responses'][$item->id]??null;if($answer)InspectionResponse::updateOrCreate(['inspection_id'=>$inspection->id,'checklist_item_id'=>$item->id],$answer);}$valid=$items->whereNotIn('id',collect($data['responses'])->filter(fn($x)=>($x['answer']??'')==='na')->keys())->sum('weight');$earned=$items->filter(fn($i)=>(($data['responses'][$i->id]['answer']??'')==='compliant'))->sum('weight');$inspection->update(['status'=>'completed','started_at'=>$inspection->started_at??now(),'completed_at'=>now(),'score'=>$valid?round($earned/$valid*100,2):100]);});$this->log('completed',$inspection,'بازرسی تکمیل و امتیاز محاسبه شد.');return back()->with('success','نتایج بازرسی ثبت شد.');}
}
