<?php
namespace App\Http\Controllers;
use App\Models\{MedicalExamination,OccupationalHealthProfile};
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Storage;
class MedicalExaminationController extends Controller {
 private function profileScope(Request $r){return OccupationalHealthProfile::with('user.department')->when($r->user()->hasRole('unit_manager'),fn($q)=>$q->whereHas('user',fn($u)=>$u->where('department_id',$r->user()->department_id)));}
 public function index(Request $r){$q=MedicalExamination::with('profile.user.department')->when($r->user()->hasRole('unit_manager'),fn($x)=>$x->whereHas('profile.user',fn($u)=>$u->where('department_id',$r->user()->department_id)));if($r->filled('q'))$q->whereHas('profile.user',fn($u)=>$u->where('name','like','%'.$r->q.'%')->orWhere('personnel_code','like','%'.$r->q.'%'));if($r->filled('type'))$q->where('examination_type',$r->type);return view('health.examinations.index',['examinations'=>$q->latest('examination_date')->paginate(15)->withQueryString()]);}
 public function create(Request $r){abort_unless($r->user()->hasRole(['admin','hse_manager']),403);$profiles=$this->profileScope($r)->orderBy('id')->get();$selected=$r->integer('profile');return view('health.examinations.form',['examination'=>new MedicalExamination(),'profiles'=>$profiles,'selectedProfile'=>$selected]);}
 public function store(Request $r){$r->merge(['follow_up_required'=>$r->boolean('follow_up_required')]);abort_unless($r->user()->hasRole(['admin','hse_manager']),403);$this->dates($r);$d=$this->validated($r);$profile=$this->profileScope($r)->findOrFail($d['occupational_health_profile_id']);$d['created_by']=$r->user()->id;$d['updated_by']=$r->user()->id;if($r->hasFile('attachment')){$f=$r->file('attachment');$d['attachment_path']=$f->store('health-exams','public');$d['attachment_name']=$f->getClientOriginalName();}unset($d['attachment']);$exam=MedicalExamination::create($d);$this->syncProfile($profile);$this->log('created',$exam,'معاینه طب کار ثبت شد.');return redirect()->route('health.profiles.show',$profile)->with('success','معاینه طب کار ثبت شد.');}
 public function edit(Request $r,MedicalExamination $examination){abort_unless($r->user()->hasRole(['admin','hse_manager']),403);$examination->load('profile.user.department');return view('health.examinations.form',['examination'=>$examination,'profiles'=>collect([$examination->profile]),'selectedProfile'=>$examination->occupational_health_profile_id]);}
 public function update(Request $r,MedicalExamination $examination){$r->merge(['follow_up_required'=>$r->boolean('follow_up_required')]);abort_unless($r->user()->hasRole(['admin','hse_manager']),403);$this->dates($r);$d=$this->validated($r);$oldProfile=$examination->profile;$profile=$this->profileScope($r)->findOrFail($d['occupational_health_profile_id']);$d['updated_by']=$r->user()->id;if($r->hasFile('attachment')){if($examination->attachment_path)Storage::disk('public')->delete($examination->attachment_path);$f=$r->file('attachment');$d['attachment_path']=$f->store('health-exams','public');$d['attachment_name']=$f->getClientOriginalName();}unset($d['attachment']);$examination->update($d);$this->syncProfile($profile);if($oldProfile->id!==$profile->id)$this->syncProfile($oldProfile);$this->log('updated',$examination,'معاینه طب کار به‌روزرسانی شد.');return redirect()->route('health.profiles.show',$profile)->with('success','معاینه طب کار به‌روزرسانی شد.');}
 private function validated(Request $r):array{return $r->validate(['occupational_health_profile_id'=>'required|exists:occupational_health_profiles,id','examination_type'=>'required|in:pre_employment,periodic,return_to_work,job_change,special,exit','examination_date'=>'required|date','health_center'=>'nullable|max:190','physician'=>'nullable|max:190','result'=>'nullable|max:5000','fitness_status'=>'required|in:fit,fit_with_restrictions,temporarily_unfit,unfit,pending','restrictions'=>'nullable|max:3000','follow_up_required'=>'nullable|boolean','follow_up_date'=>'nullable|date','next_examination_date'=>'nullable|date|after_or_equal:examination_date','notes'=>'nullable|max:5000','attachment'=>'nullable|file|max:10240|mimes:jpg,jpeg,png,pdf,doc,docx','data_source'=>'required|in:manual,healthyline,import,other','external_id'=>'nullable|max:190']);}
 private function dates(Request $r):void{foreach(['examination_date','follow_up_date','next_examination_date'] as $f)if($r->filled($f))$r->merge([$f=>optional(jalaliToCarbon($r->input($f)))->toDateString()??$r->input($f)]);}
 private function syncProfile(OccupationalHealthProfile $p):void{$last=$p->examinations()->latest('examination_date')->latest('id')->first();if(!$last){$p->update(['last_examination_date'=>null,'next_examination_date'=>null,'last_examination_type'=>null]);return;}$p->update(['last_examination_date'=>$last->examination_date,'next_examination_date'=>$last->next_examination_date,'last_examination_type'=>$last->examination_type,'fitness_status'=>$last->fitness_status,'medical_restrictions'=>$last->restrictions,'follow_up_required'=>$last->follow_up_required,'follow_up_date'=>$last->follow_up_date]);}
}
