<?php
namespace App\Http\Controllers;
use App\Models\{Department,PpeIssue,PpeRequirement,PpeType,User};
use Illuminate\Http\Request;
class PpeController extends Controller {
 public function index(Request $r){$issues=PpeIssue::with('user.department','type')->latest('issued_at')->when($r->user()->hasRole('unit_manager'),fn($q)=>$q->whereHas('user',fn($u)=>$u->where('department_id',$r->user()->department_id)))->when($r->filled('q'),fn($q)=>$q->whereHas('user',fn($u)=>$u->where('name','like','%'.$r->q.'%')))->paginate(15)->withQueryString();return view('ppe.index',compact('issues'),['types'=>PpeType::where('is_active',true)->get(),'users'=>User::where('is_active',true)->get(),'departments'=>Department::where('is_active',true)->get(),'requirements'=>PpeRequirement::with('department','type')->latest()->get()]);}
 public function storeType(Request $r){$d=$r->validate(['name'=>'required|max:190','category'=>'required|max:100','standard'=>'nullable|max:190','replacement_days'=>'required|integer|min:1|max:3650']);PpeType::create($d);return back()->with('success','نوع تجهیز حفاظت فردی ثبت شد.');}
 public function storeRequirement(Request $r){$d=$r->validate(['department_id'=>'required|exists:departments,id','job_title'=>'required|max:190','ppe_type_id'=>'required|exists:ppe_types,id','quantity'=>'required|integer|min:1|max:100','notes'=>'nullable|max:1000']);PpeRequirement::create($d);return back()->with('success','نیاز شغلی PPE ثبت شد.');}
 public function storeIssue(Request $r){$d=$r->validate(['user_id'=>'required|exists:users,id','ppe_type_id'=>'required|exists:ppe_types,id','quantity'=>'required|integer|min:1|max:100','issued_at'=>'required|date','condition'=>'required|in:new,good,used','notes'=>'nullable|max:1000']);$type=PpeType::findOrFail($d['ppe_type_id']);$d+=['expires_at'=>\Carbon\Carbon::parse($d['issued_at'])->addDays($type->replacement_days),'issued_by'=>$r->user()->id,'status'=>'issued'];PpeIssue::create($d);return back()->with('success','تحویل PPE و تاریخ تعویض ثبت شد.');}
}
