<?php
namespace App\Http\Controllers;
use App\Models\{CorrectiveAction,FmeaAnalysis,JobSafetyAnalysis,Risk,User};
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
class RiskMethodController extends Controller {
 public function createJsa(Risk $risk){$this->authorizeRisk($risk);abort_if($risk->jsa,422,'برای این ریسک قبلاً JHA/JSA ثبت شده است.');return view('risks.jsa-form',compact('risk'),['users'=>User::where('is_active',true)->get()]);}
 public function storeJsa(Request $r,Risk $risk){
  $this->authorizeRisk($risk);abort_if($risk->jsa,422,'برای این ریسک قبلاً JHA/JSA ثبت شده است.');$this->convertReviewDate($r);
  $d=$r->validate(['activity'=>'required|max:190','location'=>'nullable|max:190','owner_id'=>'required|exists:users,id','review_due_at'=>'nullable|date','steps'=>'required|array|min:1','steps.*.step'=>'required|max:1000','steps.*.hazard'=>'required|max:1000','steps.*.consequence'=>'required|max:1000','steps.*.controls'=>'nullable|max:2000','steps.*.likelihood'=>'required|integer|between:1,5','steps.*.severity'=>'required|integer|between:1,5','steps.*.residual_likelihood'=>'required|integer|between:1,5','steps.*.residual_severity'=>'required|integer|between:1,5']);
  DB::transaction(function()use($d,$risk){$jsa=JobSafetyAnalysis::create(['risk_id'=>$risk->id,'activity'=>$d['activity'],'location'=>$d['location']??null,'department_id'=>$risk->department_id,'owner_id'=>$d['owner_id'],'review_due_at'=>$d['review_due_at']??null,'status'=>'active']);foreach($d['steps'] as $i=>$s)$jsa->steps()->create($s+['sort_order'=>$i,'risk_score'=>$s['likelihood']*$s['severity'],'residual_score'=>$s['residual_likelihood']*$s['residual_severity']]);$max=$jsa->steps()->max('risk_score');$res=$jsa->steps()->max('residual_score');$risk->update(['assessment_method'=>'jsa','risk_score'=>$max,'risk_level'=>Risk::level($max),'residual_score'=>$res,'residual_level'=>Risk::level($res),'review_due_at'=>$d['review_due_at']??null,'owner_id'=>$d['owner_id']]);});
  $this->log('jsa_created',$risk,'تحلیل JHA/JSA به ریسک موجود متصل شد.');return redirect()->route('risks.show',$risk)->with('success','تحلیل JHA/JSA ثبت شد.');
 }
 public function createFmea(Risk $risk){$this->authorizeRisk($risk);abort_if($risk->fmea,422,'برای این ریسک قبلاً FMEA ثبت شده است.');return view('risks.fmea-form',compact('risk'),['users'=>User::where('is_active',true)->get()]);}
 public function storeFmea(Request $r,Risk $risk){
  $this->authorizeRisk($risk);abort_if($risk->fmea,422,'برای این ریسک قبلاً FMEA ثبت شده است.');$this->convertReviewDate($r);
  $d=$r->validate(['process'=>'required|max:190','function'=>'required|max:500','owner_id'=>'required|exists:users,id','review_due_at'=>'nullable|date','items'=>'required|array|min:1','items.*.failure_mode'=>'required|max:1000','items.*.effect'=>'required|max:1000','items.*.cause'=>'required|max:1000','items.*.existing_control'=>'nullable|max:2000','items.*.severity'=>'required|integer|between:1,10','items.*.occurrence'=>'required|integer|between:1,10','items.*.detection'=>'required|integer|between:1,10','items.*.recommended_action'=>'nullable|max:2000']);
  DB::transaction(function()use($d,$risk){$fmea=FmeaAnalysis::create(['risk_id'=>$risk->id,'process'=>$d['process'],'function'=>$d['function'],'department_id'=>$risk->department_id,'owner_id'=>$d['owner_id'],'review_due_at'=>$d['review_due_at']??null,'status'=>'active']);foreach($d['items'] as $i=>$item)$fmea->items()->create($item+['sort_order'=>$i,'rpn'=>$item['severity']*$item['occurrence']*$item['detection']]);$risk->update(['assessment_method'=>'fmea','review_due_at'=>$d['review_due_at']??null,'owner_id'=>$d['owner_id']]);});
  $this->log('fmea_created',$risk,'تحلیل FMEA با محاسبه خودکار RPN ثبت شد.');return redirect()->route('risks.show',$risk)->with('success','تحلیل FMEA ثبت شد.');
 }
 public function createActionFromFmea(Request $r,FmeaAnalysis $fmea){$risk=$fmea->risk;$this->authorizeRisk($risk);if($r->filled('due_date')&&str_contains($r->due_date,'/'))$r->merge(['due_date'=>optional(jalaliToCarbon($r->due_date))?->toDateString()??$r->due_date]);$d=$r->validate(['item_id'=>'required|exists:fmea_items,id','assignee_id'=>'required|exists:users,id','due_date'=>'required|date|after_or_equal:today']);$item=$fmea->items()->findOrFail($d['item_id']);$action=CorrectiveAction::create(['code'=>$this->code('ACT'),'title'=>'اقدام FMEA: '.$item->failure_mode,'description'=>$item->recommended_action?:'کنترل و کاهش RPN مورد شناسایی‌شده در FMEA','actionable_type'=>$risk::class,'actionable_id'=>$risk->id,'department_id'=>$risk->department_id,'assignee_id'=>$d['assignee_id'],'assigned_by'=>$r->user()->id,'priority'=>$item->rpn>=300?'critical':($item->rpn>=150?'high':'medium'),'due_date'=>$d['due_date'],'status'=>'assigned']);$this->log('assigned',$action,'اقدام اصلاحی از FMEA ایجاد شد.');return back()->with('success','اقدام اصلاحی از آیتم FMEA ساخته شد.');}
 private function authorizeRisk(Risk $risk):void{$u=auth()->user();abort_unless($u->hasRole(['admin','hse_manager','inspector']),403);abort_if($u->hasRole('inspector')&&$risk->identified_by!==$u->id,403);}
 private function convertReviewDate(Request $r):void{if($r->filled('review_due_at'))$r->merge(['review_due_at'=>optional(jalaliToCarbon($r->review_due_at))?->toDateString()??$r->review_due_at]);}
}
