<?php
namespace App\Http\Controllers;
use App\Models\{Department,SafetyEquipment};
use Illuminate\Http\Request;
class SafetyEquipmentController extends Controller {
 public function index(Request $r){$q=SafetyEquipment::with('department')->latest();if($r->user()->hasRole('unit_manager'))$q->where('department_id',$r->user()->department_id);if($r->filled('q'))$q->where(fn($x)=>$x->where('name','like','%'.$r->q.'%')->orWhere('code','like','%'.$r->q.'%')->orWhere('serial_number','like','%'.$r->q.'%'));if($r->filled('status'))$q->where('status',$r->status);return view('equipment.index',['equipment'=>$q->paginate(15)->withQueryString(),'departments'=>Department::where('is_active',true)->get()]);}
 public function store(Request $r){$d=$r->validate(['code'=>'required|max:80|unique:safety_equipments','name'=>'required|max:190','type'=>'required|in:fire_extinguisher,alarm,detector,first_aid,emergency,other','department_id'=>'required|exists:departments,id','location'=>'required|max:190','serial_number'=>'nullable|max:190','inspection_interval_days'=>'required|integer|min:1|max:3650','service_interval_days'=>'required|integer|min:1|max:3650','last_inspected_at'=>'nullable|date','last_serviced_at'=>'nullable|date','expiry_date'=>'nullable|date','notes'=>'nullable|max:2000']);$d['next_inspection_at']=!empty($d['last_inspected_at'])?\Carbon\Carbon::parse($d['last_inspected_at'])->addDays($d['inspection_interval_days']):today();$d['next_service_at']=!empty($d['last_serviced_at'])?\Carbon\Carbon::parse($d['last_serviced_at'])->addDays($d['service_interval_days']):today();$d['status']='active';SafetyEquipment::create($d);return back()->with('success','تجهیز ایمنی ثبت شد.');}
 public function inspect(Request $r,SafetyEquipment $equipment){$d=$r->validate(['operation'=>'required|in:inspection,service,recharge','date'=>'required|date','notes'=>'nullable|max:2000']);if($d['operation']==='inspection')$equipment->update(['last_inspected_at'=>$d['date'],'next_inspection_at'=>\Carbon\Carbon::parse($d['date'])->addDays($equipment->inspection_interval_days),'notes'=>$d['notes']??$equipment->notes]);else $equipment->update(['last_serviced_at'=>$d['date'],'next_service_at'=>\Carbon\Carbon::parse($d['date'])->addDays($equipment->service_interval_days),'notes'=>$d['notes']??$equipment->notes]);return back()->with('success','سابقه بازرسی/سرویس تجهیز به‌روزرسانی شد.');}
}
