<?php
namespace App\Http\Controllers;
use App\Models\{Department,SafetyEquipment};
use Illuminate\Http\Request;
class SafetyEquipmentController extends Controller {
 public function index(Request $r){$q=SafetyEquipment::with('department')->latest();if($r->user()->hasRole('unit_manager'))$q->where('department_id',$r->user()->department_id);if($r->filled('q'))$q->where(fn($x)=>$x->where('name','like','%'.$r->q.'%')->orWhere('code','like','%'.$r->q.'%')->orWhere('serial_number','like','%'.$r->q.'%'));if($r->filled('status'))$q->where('status',$r->status);return view('equipment.index',['equipment'=>$q->paginate(15)->withQueryString(),'departments'=>Department::where('is_active',true)->get()]);}
 public function store(Request $r){$this->convertJalaliDates($r,['last_inspected_at','last_serviced_at','last_recharged_at','expiry_date']);$d=$r->validate(['code'=>'required|max:80|unique:safety_equipments','name'=>'required|max:190','type'=>'required|in:fire_extinguisher,alarm,detector,first_aid,emergency,other','department_id'=>'required|exists:departments,id','location'=>'required|max:190','serial_number'=>'nullable|max:190','inspection_interval_days'=>'required|integer|min:1|max:3650','service_interval_days'=>'required|integer|min:1|max:3650','recharge_interval_days'=>'nullable|integer|min:1|max:3650','last_inspected_at'=>'nullable|date','last_serviced_at'=>'nullable|date','last_recharged_at'=>'nullable|date','expiry_date'=>'nullable|date','notes'=>'nullable|max:2000']);$d['recharge_interval_days']=$d['recharge_interval_days']??$d['service_interval_days'];$d['next_inspection_at']=!empty($d['last_inspected_at'])?\Carbon\Carbon::parse($d['last_inspected_at'])->addDays($d['inspection_interval_days']):today();$d['next_service_at']=!empty($d['last_serviced_at'])?\Carbon\Carbon::parse($d['last_serviced_at'])->addDays($d['service_interval_days']):today();$d['next_recharge_at']=!empty($d['last_recharged_at'])?\Carbon\Carbon::parse($d['last_recharged_at'])->addDays($d['recharge_interval_days']):today();$d['status']='active';SafetyEquipment::create($d);return back()->with('success','تجهیز ایمنی ثبت شد.');}
 public function inspect(Request $r,SafetyEquipment $equipment){$this->convertJalaliDates($r,['date']);$d=$r->validate(['operation'=>'required|in:inspection,service,recharge','date'=>'required|date','notes'=>'nullable|max:2000']);$date=\Carbon\Carbon::parse($d['date']);$rechargeInterval=$equipment->recharge_interval_days?:($equipment->service_interval_days?:365);$fields=match($d['operation']){ 'inspection'=>['last_inspected_at'=>$d['date'],'next_inspection_at'=>$date->copy()->addDays($equipment->inspection_interval_days)], 'service'=>['last_serviced_at'=>$d['date'],'next_service_at'=>$date->copy()->addDays($equipment->service_interval_days)], 'recharge'=>['last_recharged_at'=>$d['date'],'next_recharge_at'=>$date->copy()->addDays($rechargeInterval),'recharge_interval_days'=>$rechargeInterval],};$equipment->update($fields+['notes'=>$d['notes']??$equipment->notes]);return back()->with('success','سابقه تجهیز به‌روزرسانی شد.');}
 private function convertJalaliDates(Request $request,array $fields):void{foreach($fields as $field)if($request->filled($field))$request->merge([$field=>optional(jalaliToCarbon($request->input($field)))->toDateString()??$request->input($field)]);}
}
